### ISSUE TITLE
Ruby Sass has reached end-of-life and should no longer be used.

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#1012]
Ruby Sass has reached end-of-life and should no longer be used.
* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

**Comment by CloCkWeRX** [comment]
sassc for now, but should review
https://dev.to/kolide/how-to-migrate-a-rails-6-app-from-sass-rails-to-cssbundling-rails-4l41

**Comment by brian-kephart** [comment]
I know this issue is closed, but if you wish to avoid the larger migration to cssbundling-rails, checkout [dartsass-sprockets](https://github.com/tablecheck/dartsass-sprockets). It's a drop-in replacement for sassc-rails that uses up-to-date dartsass.

**Comment by johnnyshields** [comment]
+1 for dartsass-sprockets, I'm the maintainer of it (and coincidentally a maintainer of fat_free_crm too!)
