### ISSUE TITLE
Escape mandatory field for 'Last name' in Lead creation form

### ISSUE THREAD

**Issue by SonalikaG** [fatfreecrm/fat_free_crm#1018]
Could you please suggest a way to escape the 'Last name' field in Lead creation form. Is there any way we can make it non-mandatory?

![image](https://user-images.githubusercontent.com/72000677/195103413-b51507f8-0928-4fbc-9797-5ecbe2fd0271.png)

**Comment by steveyken** [comment]
Hi, there is a Setting called `require_last_names` that you can change to false.

See
https://github.com/fatfreecrm/fat_free_crm/blob/master/config/settings.default.yml#L159-L163

and 
https://github.com/fatfreecrm/fat_free_crm/blob/master/app/models/entities/lead.rb#L78
