### ISSUE TITLE
Improve spec coverage

### ISSUE THREAD

**Issue by Jaskaran2** [fatfreecrm/fat_free_crm#1048]
Hi I noticed there a few files where spec coverage can be increased is it ok if I raise a PR to increase the overall spec coverage
<img width="1426" alt="Screenshot 2023-01-22 at 1 20 26 AM" src="https://user-images.githubusercontent.com/60808292/213884704-5f7745ba-71fa-4adf-9d6b-f5d3dee93e29.png">

**Comment by CloCkWeRX** [comment]
https://thinkinglabs.io/articles/2022/03/19/the-fallacy-of-the-100-code-coverage.html
