### ISSUE TITLE
Error loading page: DEPRECATION WARNING: Initialization autoloaded the constant Setting.

### ISSUE THREAD

**Issue by MaysenTG** [fatfreecrm/fat_free_crm#1134]
Hey all, I'm getting an error when trying to load a page after booting the app that a constant object was auto loaded on initialisation. See below for a screenshot of the logs showing that error:

![alt](https://s3.amazonaws.com/hso-monosnap/2023-07-18_10_PM-20-03.png)

All I've done with the app is following the setup instructions (bundle install, db:setup, etc) but I'm not sure why I seem to be the only one experiencing this issue? I'm on an Macbook Pro (M2 Pro chip) if that changes anything? Seems to be related to calling model classes within the `/lib` or `/config` directory

**Comment by CloCkWeRX** [comment]
See https://github.com/fatfreecrm/fat_free_crm/pull/1115/files#diff-d3c4b3f41072daa416f1920511e9b2e26caea8c5cec0a14cb9508589a4dafa47
