### ISSUE TITLE
Ruby 2.7 has reached EOL

### ISSUE THREAD

**Issue by ferrisoxide** [fatfreecrm/fat_free_crm#1138]
Ruby 2.7 (specified in `.ruby-version`) reached EOL as of 31 Mar 2023. FatFreeCRM currently defaults to Ruby 2.7.5. 

Upgrading to a supported 3.x version would probably help development going foward. For instance, the `mini_racer` gem is only [supported on non-EOL](https://github.com/rubyjs/mini_racer#supported-ruby-versions--troubleshooting) Ruby versions.

It's probably worth upgrading to a 3.0.x version, then look to progressively upgrade to later Rubies once any issues have been resolved.

**Comment by ferrisoxide** [comment]
PR for this: #1139

**Comment by CloCkWeRX** [comment]
Alright, released as v0.21.0
