### ISSUE TITLE
Roadmap / current status

### ISSUE THREAD

**Issue by ferrisoxide** [fatfreecrm/fat_free_crm#1143]
Hi folks

Not sure if this is the best place to ask these sorts of questions, but the Google Groups don't appear to have much traffic at the moment. Apologies is this isn't the right forum.

* Are there plans to "modernize" the code base? For example, using Hotwire / Rails 7 / etc?
* Is there a road map for where the project is headed, or is it considered "feature complete"?
* Is anyone offering hosting services for the application?
 
I'm really keen on using FFCrm - and admire the philosophy behind keeping it "fat free". I'm happy to contribute to the project, but I just want to get a feel for the current state of things - where the project is going and what problems need to be solved. Any advice appreciated.

Again, apologies if this isn't the right place to ask this. 

Cheers
Tom

**Comment by CloCkWeRX** [comment]
Pull Requests welcome.

**Comment by ferrisoxide** [comment]
> Pull Requests welcome.

Happy to create pull requests - and have already provided a couple - but the questions were more where the project is going, and what sort of ecosystem exists around it.

It sounds like the direction of the project will be determined by PRs provided by the community - is that correct?

Just trying to make sure that any contribution I make is actually valuable. If there is a vision for the project, I'm keen to work within and towards that. If the project is more _ad hoc_, then that's fine too.
