### ISSUE TITLE
Actions on activity fails

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#1254]
![Screenshot_20240310-234411](https://github.com/fatfreecrm/fat_free_crm/assets/365751/d3e71228-8539-451f-a97f-882c01e8749d)
https://growstuff-staging.herokuapp.com/activities/clockwerx-rehydrate-arrakis#

**Comment by CloCkWeRX** [comment]
![Screenshot_20240310-234553](https://github.com/fatfreecrm/fat_free_crm/assets/365751/a215aa4b-4de6-4812-be04-92f14b533987)
Additionally while some actions are available, no way to "do" them

**Comment by steveyken** [comment]
Is this FFCRM related or ... ? :)

**Comment by steveyken** [comment]
Think I might close this one as unrelated to fat_free_crm itself :)
