### ISSUE TITLE
Alternative names not being matched for autocomplete?

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#1255]
![Screenshot_20240310-235034](https://github.com/fatfreecrm/fat_free_crm/assets/365751/0e8ae9c1-5a7e-4194-91e3-28e19bcad990)
But:
- My partner did a planting
- searched for aubergine
- did not get successful recommendations

**Comment by steveyken** [comment]
Is this FFCRM related or ... ? :)

**Comment by CloCkWeRX** [comment]
And that'll learn me to do this at the pub!
