### ISSUE TITLE
0.23 release or 0.22.1?

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#1336]
@steveyken there has been a fair bit of work, you have been a bit more active than I have in terms of regression testing - worth cutting a 0.22.1 release with current features?

**Comment by steveyken** [comment]
Yes, I think a 0.22.1 release now would be good. Lots of bug fixes and
stability.

I have some ransack_ui updates in pipeline but that would be better in 0.23
as it bumps the ransack and select2 versions (but still backwards
compatible).

Would like to see Rails 7.2 update soon too. Defo target 0.23+ for that.

**Comment by CloCkWeRX** [comment]
https://github.com/fatfreecrm/fat_free_crm/releases/tag/v0.22.1 done as a tag.

If you are near a keyboard, feel free to build and publish, otherwise I will in the next 12-24 hours

**Comment by steveyken** [comment]
I've updated `lib/fat_free_crm/version.rb` and pushed that change to the 0.22.x branch. Does that update the 0.22.1 release tag?

I've also released the gem to rubygems. https://rubygems.org/gems/fat_free_crm/versions/0.22.1 using the following:

```
git checkout 0.22.x
gem build
gem push fat_free_crm-0.22.1.gem
```

**Comment by steveyken** [comment]
We're currently working on Rails 7.0 -> 7.1 -> 7.2 upgrade. That can go in the 0.23 release. Will close this ticket now.
