### ISSUE TITLE
Branch 0.22.x ActionView::Template::Error (Tried to load unspecified class: Set):

### ISSUE THREAD

**Issue by cchavez** [fatfreecrm/fat_free_crm#1369]
Hi all I'm updating from the version 0.19.0 to the 0.22.x after manage an issue with some migration see that on the ticket #1262, I got the error **ActionView::Template::Error (Tried to load unspecified class: Set):**

After some searching I found some recommendation that add the Set to the **config/application.rb** which I did on the variable **config.active_record.yaml_column_permitted_classes**, I added **::Set** but the error change to:

**ActionView::Template::Error (can't load `subscribed_users`: was supposed to be a Array, but was a Set. -- #<Set: {2}>):**

I'm using ruby 3.3.5.

**Comment by CloCkWeRX** [comment]
https://github.com/search?q=repo%3Afatfreecrm%2Ffat_free_crm%20subscribed_users&type=code - this data has been serialised as an array since 2012.

**Comment by cchavez** [comment]
> https://github.com/search?q=repo%3Afatfreecrm%2Ffat_free_crm%20subscribed_users&type=code - this data has been serialised as an array since 2012.

I'm not asking to change to use Set, the thing is that the application it self shows the error:

ActionView::Template::Error (Tried to load unspecified class: Set):

So, what should be the steps that I need to do to fix that issue on my side?

**Comment by cchavez** [comment]
> https://github.com/search?q=repo%3Afatfreecrm%2Ffat_free_crm%20subscribed_users&type=code - this data has been serialised as an array since 2012.

Hi @CloCkWeRX 

The change of the field to be an Array is more recent than the migration.

Please check the git blame of that line and is about 2 years ago but the migration is pretty much older.

https://github.com/fatfreecrm/fat_free_crm/blame/2fa87a36b0d2dd8cda51072dfb2e11ed4b95b18c/app/models/entities/campaign.rb#L42

So, my thinking is that someone change that line without taking in count that migration or maybe create another migration to rollback to a Array in the database to Serialize correctly.

The migration convert to a Set the value.

**Comment by cchavez** [comment]
> > https://github.com/search?q=repo%3Afatfreecrm%2Ffat_free_crm%20subscribed_users&type=code - this data has been serialised as an array since 2012.
> 
> Hi @CloCkWeRX
> 
> The change of the field to be an Array is more recent than the migration.
> 
> Please check the git blame of that line and is about 2 years ago but the migration is pretty much older.
> 
> https://github.com/fatfreecrm/fat_free_crm/blame/2fa87a36b0d2dd8cda51072dfb2e11ed4b95b18c/app/models/entities/campaign.rb#L42
> 
> So, my thinking is that someone change that line without taking in count that migration or maybe create another migration to rollback to a Array in the database to Serialize correctly.
> 
> The migration convert to a Set the value.

If the field will keep as Array, I think I will to convert back to Array on my side.
