### ISSUE TITLE
Can't access password change form on devise branch

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#243]
Steps to reproduce:
- Login
- Go to user profile.
- Click 'Change password'

What happens?
- ActionView::Template::Error (undefined local variable or method `passwords_path'

**Comment by cypa** [comment]
Dear @steveyken whats up with devise branch?
Since I'm a newbie to ruby could you, please, provide detailed plan for devise integration for us to do step-by-step coding?

**Comment by johnnyshields** [comment]
Please close this issue; Devise branch is not supported and this issue will be fixed when we switch to Devise.
