### ISSUE TITLE
ransack_ui has horrible performance

### ISSUE THREAD

**Issue by hubrix** [fatfreecrm/fat_free_crm#260]
3,960   

54.64%
    entities/_search.html.haml Partial      0.268  s
15.0    

0.21%
    entities/_basic_search.html.haml Partial        0.270  s
3,950   

54.41%
    ransack_ui/_search.html.erb Partial         0.285  s
228     

3.14%
    ransack_ui/_sort_fields.html.erb Partial        0.290  s
1,680   

23.20%
    ransack_ui/_grouping_fields.html.erb Partial        0.522  s
929     

12.81%
    ransack_ui/_condition_fields.html.erb Partial       0.524  s
742     

10.23%
    ransack_ui/_condition_fields.html.erb Partial       1.454  s
2,020   

27.79%
    ransack_ui/_grouping_fields.html.erb Partial        2.209  s
1,280   

17.64%
    ransack_ui/_condition_fields.html.erb Partial       2.210  s
732     

10.10%
    ransack_ui/_condition_fields.html.erb Partial       3.490  s

**Comment by steveyken** [comment]
We're updating to the latest ransack versions (1.5) in the rails4 branch. I'm hoping this issue will go away...but haven't tested it yet.

**Comment by johnnyshields** [comment]
I think this has gotten better and can be closed.
