### ISSUE TITLE
Consider removing user.last_request_at

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#271]
last_request_at is updated with every request a user makes.

However, the only place it appears used is
app/views/admin/users/_user.html.haml

```
      - elsif user.last_request_at
        %span.cool #{t(:last_seen, time_ago_in_words(user.last_request_at))}
```

to generate 'last seen' text.

Recommendations
 * Consider updating this only on POST, PUT, DELETE (modifcations)
 * Alternatively, only on login/new session/logout - renaming it "last_login"
 * Or removing it entirely. The audit use case is minimal and possible to work out via paper trail anyway, afaict.

**Comment by steveyken** [comment]
This has been completed in #430
