### ISSUE TITLE
CSV mass update feature

### ISSUE THREAD

**Issue by SimonGabris** [fatfreecrm/fat_free_crm#339]
Hi There,

I know all crm has mass updating as a common feature.
Do you have any csv import functionality in Admin area?

**Comment by nicholassewitz** [comment]
Hey Steve it looks like your importer only supports rails 3 while FFCRM has been updated to rails 4. I dont think they can work in conjunction. Any way to update the importer pleasE?

**Comment by steveyken** [comment]
Good point. You're right, that plugin will not work with the latest FFCRM.
I'm not the maintainer but it is open source so if there's a spare moment
at some point, I might be able to take a look and make a rails4 branch of
it.
