### ISSUE TITLE
Missing Git repo on Cap 3 deploy

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#352]
Somehow, the Git repo is not deployed when using Capistrano 3 deploy. Otherwise, it is successful, but I'm getting loads of this:

``` sh
fatal: Not a git repository (or any of the parent directories): .git
```

I'm suspecting it's a conflict of some sorts with other gems. Any related experiences?

**Comment by Startouf** [comment]
I'm still running into similar issues, did you find the bug ?

**Comment by papilip** [comment]
Hi, i have the same issue, i make a PR #522 for remove git command in fat_free_crm.gemspec

**Comment by ain** [comment]
Closing since #522 was merged.
