### ISSUE TITLE
Cannot convert a lead

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#380]
1. Goto a lead and click 'convert'
2. Fill in the form and submit

Error

    ActionController::RoutingError (No route matches [PATCH] "/leads/120/promote"):

**Comment by steveyken** [comment]
The route works now but still doesn't convert for me. I get the 'shaky' box of invalidation

**Comment by warp** [comment]
All the leads I tried appeared to convert I might need some more details to reproduce this one.

**Comment by steveyken** [comment]
Can't reproduce. Calling this fixed. :)
