### ISSUE TITLE
Sorting custom fields throws error

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#386]
* Goto /admin/fields
* Create at least 2 custom fields
* Re-order them

Server error:

    Started POST "/admin/fields/sort?field_group_id=1" for 127.0.0.1 at 2015-01-02 10:42:35 +0800
    Processing by Admin::FieldsController#sort as */*
      Parameters: {"fields_field_group_1"=>["2", "3", "4", "5", "6", "7", "8", "9", "10", "17", "11", "12", "13", "14", "15", ""], "field_group_id"=>"1"}
    Completed 500 Internal Server Error in 27ms

    ArgumentError (wrong number of arguments (2 for 1)):
      app/controllers/admin/fields_controller.rb:89:in `block in sort'
      app/controllers/admin/fields_controller.rb:88:in `each'
      app/controllers/admin/fields_controller.rb:88:in `each_with_index'
      app/controllers/admin/fields_controller.rb:88:in `sort'

**Comment by warp** [comment]
resolved by https://github.com/fatfreecrm/fat_free_crm/commit/7a226cd3e05f554224d2764a414a9cbe8105d08f
