### ISSUE TITLE
Installing Rails 4 branch as an Engine produces jquery-rails gem error

### ISSUE THREAD

**Issue by colakatz** [fatfreecrm/fat_free_crm#387]
By default a Rails 4.1 app uses the latest version of the jquery-rails gem, which is >= 3.1 currently.  The jquery-rails gem in the FFCRM gemspec file is locked to 2.1.4, when running a "Bundle Install", this produces an error, thus not allowing you to install it as an engine

The easy way to get around this for the "Bundle Install" is to set the version in the rails gem file to "~> 2.1.4".

**Comment by steveyken** [comment]
@warp we are locked to jQuery 1.8 but Rails 4.1 goes for jQuery 1.11 and up... what sort of a migration job do you think this would be?

see https://github.com/rails/jquery-rails/blob/master/VERSIONS.md

**Comment by warp** [comment]
I have updated to latest jquery-rails in https://github.com/fatfreecrm/fat_free_crm/commit/1107ee54e574c985fe9f6907f981e14e6c3ddb8d everything appears to be working as expected I included jquery migrate to provide the browser detect functionality that has been removed. Let me know if you spot anything else broken.

**Comment by steveyken** [comment]
Will do thanks. I didn't know about jquery-migrate - looks very handy for this sort of application.
