### ISSUE TITLE
FFCRM as Rails Engine on Rails 4-- undefined method `engines' for Rails::Engine::Railties:Class

### ISSUE THREAD

**Issue by melissawahnish** [fatfreecrm/fat_free_crm#394]
Hi!  I would love to use FFCRM on a project in Rails 4.1 and see you are currently testing for the upgrade.  I have used FFCRM before for a rails 3.2 project.

Note: I'm using a local version of the gem pulled from the rails4 branch yesterday (1/5/15).  I had to change the fat_free_crm.gemspec to site a newer version of ransack to get this far.

Using the currently tutorial as a guide, I got up to where you add this method to application.rb:

    Railties.engines.each do |engine|
      config.paths['db/migrate'] += engine.paths['db/migrate'].existent
    end

I get this message when I run rake ffcrm:setup 

  rake aborted!
  NoMethodError: undefined method `engines' for Rails::Engine::Railties:Class

Per http://apidock.com/rails/Rails/Application/Railties/engines, the engines method was deprecated.  Not sure what to now...

I'm happy to help in any way I can.  Thanks!

**Comment by steveyken** [comment]
Thanks, I actually just started looking at this yesterday too, but hadn't got quite as far, so this is very helpful. I'll do a bit more work on it this week and see where we get too. We'll need to update the guide to too. Feel free to write more rails4 engine related notes here as you come across them. Thanks!

**Comment by warp** [comment]
I have updated the rails 4 branch to run correctly as an engine in https://github.com/fatfreecrm/fat_free_crm/commit/3183873e28f112895a70cdc41979d8705dfbd5bd
you can now remove
```
Railties.engines.each do |engine|
  config.paths['db/migrate'] += engine.paths['db/migrate'].existent
end
```
as this is now handled by the engine

**Comment by melissawahnish** [comment]
Thanks!  Engine now works!  I saw a few front end bugs that I will list in a new issue.

**Comment by steveyken** [comment]
If it's of interest, to help with debugging issues when running FFCRM as an engine, I've created the following reference project: https://github.com/fatfreecrm/ffcrm_app41
