### ISSUE TITLE
Rails 4 (using FFCRM as engine) - asset_path breaks views

### ISSUE THREAD

**Issue by melissawahnish** [fatfreecrm/fat_free_crm#396]
After logging in for the first time I found that in app/views/lists/_sidebar.html.haml, line 23 breaks the view as asset_path is no longer used:

= image_tag(asset_path('info_tiny.png'), :title => t(:list_name_info), class: "input_info")

This works instead
= image_tag 'info_tiny.png', :title => t(:list_name_info), class: "input_info"

**Comment by steveyken** [comment]
Thanks, a3dc393 fixes this

**Comment by melissawahnish** [comment]
Thanks.  Works fine now. :)
