### ISSUE TITLE
Entering existing Account doesn't save

### ISSUE THREAD

**Issue by melissawahnish** [fatfreecrm/fat_free_crm#397]
I found these using the rails4 branch but they are also on the master branch.  They are super nit-picky and edge case. 

1)To produce error -- Click on Contacts, click on Create Contact, add first and last name, enter an existing Account, click Create Contact. 

Page does nothing.  If you refresh, the Contact is created but without the Account. 

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"accounts", :format=>nil, :id=>#<Account id: nil, user_id: 1, assigned_to: nil, name: "Uline", access: "Public", website: nil, toll_free_phone: nil, phone: nil, fax: nil, deleted_at: nil, created_at: nil, updated_at: nil, email: nil, background_info: nil, rating: 0, category: nil, subscribed_users: #<Set: {}>>} missing required keys: [:id]):

Using the select existing account dropdown works fine, but what if the user forgets he has created that account?  Also my browser (Firefox on Ubuntu) gave me an autocomplete option which made me think that selecting the autocomplete would work.

2) To produce error -- Click on Opportunities, click on Create Opportunity, add first and last name, enter an existing Account , click Create Opportunity
Page shows list of Opportunities but the Opportunity was created without reference to Account.

**Comment by unijewski** [comment]
I believe it's fixed in my pull request.
