### ISSUE TITLE
Quick Find hides results

### ISSUE THREAD

**Issue by melissawahnish** [fatfreecrm/fat_free_crm#398]
The Quick find hides the results just a bit.  See attached.  This was on Firefox on Ubuntu.
![screenshot-localhost 3000 2015-01-07 11-47-00](https://cloud.githubusercontent.com/assets/3316838/5649689/e3e1acb0-9665-11e4-9843-873ed6a03b51.png)

**Comment by steveyken** [comment]
Also seen in the ffcrm_merge plugin (which uses the same underlying js) using Chrome browser

**Comment by unijewski** [comment]
The problem appears on `rails4` branch. To be honest, I'm not sure whether my solution is the best (I'm not familiar with the CRM) but it works.
