### ISSUE TITLE
NoMethodError (undefined method `each' for nil:NilClass) when run as an engine

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#399]
I get an error accessing the dashboard when running Fat Free CRM as an engine.

I've created an app to help test Fat Free CRM in engine mode.

Steps to reproduce:

    git clone https://github.com/fatfreecrm/ffcrm_app41.git
    bundle install
    rake db:create
    rake db:migrate
    rake ffcrm:demo:load
    bin/rails s

Now goto http://localhost:3000 and login as username `aaron` password `aaron`

Get the following error on accessing home page.

    NoMethodError (undefined method `each' for nil:NilClass):
      activerecord (4.1.0) lib/active_record/associations/preloader/association.rb:87:in `block in associated_records_by_owner'
      activerecord (4.1.0) lib/active_record/associations/preloader/association.rb:86:in `each'
      activerecord (4.1.0) lib/active_record/associations/preloader/association.rb:86:in `associated_records_by_owner'
      activerecord (4.1.0) lib/active_record/associations/preloader/singular_association.rb:9:in `preload'
      activerecord (4.1.0) lib/active_record/associations/preloader/association.rb:20:in `run'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:136:in `block (2 levels) in preloaders_for_one'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:134:in `each'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:134:in `map'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:134:in `block in preloaders_for_one'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:133:in `each'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:133:in `flat_map'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:133:in `preloaders_for_one'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:117:in `preloaders_for_hash'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:104:in `preloaders_on'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:94:in `block in preload'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:93:in `each'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:93:in `flat_map'
      activerecord (4.1.0) lib/active_record/associations/preloader.rb:93:in `preload'
      activerecord (4.1.0) lib/active_record/relation.rb:609:in `block in exec_queries'
      activerecord (4.1.0) lib/active_record/relation.rb:608:in `each'
      activerecord (4.1.0) lib/active_record/relation.rb:608:in `exec_queries'
      activerecord (4.1.0) lib/active_record/relation.rb:487:in `load'
      activerecord (4.1.0) lib/active_record/relation.rb:231:in `to_a'
      /home/steve/.rvm/gems/ruby-2.1.1/bundler/gems/fat_free_crm-a3dc3930701c/app/models/polymorphic/version.rb:64:in `visible_to'
      activerecord (4.1.0) lib/active_record/relation/delegation.rb:94:in `public_send'
      activerecord (4.1.0) lib/active_record/relation/delegation.rb:94:in `block in method_missing'
      activerecord (4.1.0) lib/active_record/relation.rb:286:in `scoping'
      activerecord (4.1.0) lib/active_record/relation/delegation.rb:94:in `method_missing'
      /home/steve/.rvm/gems/ruby-2.1.1/bundler/gems/fat_free_crm-a3dc3930701c/app/controllers/home_controller.rb:100:in `get_activities'
      /home/steve/.rvm/gems/ruby-2.1.1/bundler/gems/fat_free_crm-a3dc3930701c/app/controllers/home_controller.rb:12:in `index'

**Comment by warp** [comment]
Interesting the rails 4.2 branch I was testing against does not have this issue so lets merge in rails 4.2 and run with that.

**Comment by steveyken** [comment]
yup, this has gone away with 4.2
