### ISSUE TITLE
ActionView::Template::Error (undefined method `username' for #<Authentication: no credentials provided>) when running as an engine

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#400]
* Download and run the FFCRM reference app engine at https://github.com/fatfreecrm/ffcrm_app42
* Run the engine in production mode (don't forget RAILS_ENV=production rake assets:precompile)
* Goto http://localhost:3000

The following error occurs

    I, [2015-01-08T16:37:28.352899 #18780]  INFO -- : Started GET "/login" for 127.0.0.1 at 2015-01-08 16:37:28 +0800
    I, [2015-01-08T16:37:28.425325 #18780]  INFO -- : Processing by AuthenticationsController#new as HTML
    I, [2015-01-08T16:37:28.796128 #18780]  INFO -- :   Rendered /home/steve/.rvm/gems/ruby-2.1.1/bundler/gems/fat_free_crm-a3dc3930701c/app/views/authentications/
    new.html.haml within layouts/application (7.9ms)
    I, [2015-01-08T16:37:28.796409 #18780]  INFO -- : Completed 500 Internal Server Error in 371ms
    F, [2015-01-08T16:37:28.801306 #18780] FATAL -- : 
    ActionView::Template::Error (undefined method `username' for #<Authentication: no credentials provided>):
         7:     .title= t(:login)
         8:     .section
         9:       .label= t(:username) + ':'
        10:       = f.text_field :username
        11:       .label= t(:password) + ':'
        12:       = f.password_field :password

**Comment by steveyken** [comment]
This is still a problem after running the latest rails 4.2 merged code.

**Comment by warp** [comment]
ok I'll take a look at this one tonight

**Comment by warp** [comment]
I can't reproduce this one have you tried clearing your session cookies :)

**Comment by steveyken** [comment]
I'll give it another go now that ransack issue is fixed

**Comment by steveyken** [comment]
This is still a problem in when running an engine in production mode. I've cleared all cache in case it was a stale session

**Comment by steveyken** [comment]
Created https://github.com/fatfreecrm/ffcrm_app42 to try to help with reproducing the problem.

**Comment by steveyken** [comment]
I've done the following to reproduce this:

    git clone https://github.com/fatfreecrm/ffcrm_app42.git
    rvm gemset create ffcrm_app42
    rvm use 2.1.5@ffcrm_app42
    bundle install
    rake assets:precompile
    bin/rails s -e production

Visit http://localhost:3000/ in incognito / cleared cache / another browser.

**Comment by warp** [comment]
hmm so I followed all the instructions except I used ruby 2.2.0 built with
ruby build rather than rvm and it worked fine. Possible its the ruby
version I guess but its hard to see how?

**Comment by steveyken** [comment]
Ok so I've finally worked out what I did wrong...

Looks like you can't share development and production DB's anymore so hotwiring my production DB to use my development DB causes the error (I often do that to save setup time in production mode if I'm testing a small feature) Time to unlearn the habit!
