### ISSUE TITLE
Ransack 1.6 released

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#409]
We should update the rails4 branch to use this. Currently pegged to 1.5. perhaps make that a >=1.5

**Comment by warp** [comment]
yeah I tried and it was broken already :(

**Comment by warp** [comment]
resolved by https://github.com/fatfreecrm/fat_free_crm/commit/99f4e1f4269054fc85980ce64e04bcf12b3ed66a
