### ISSUE TITLE
e-mail address with with accidently added spaces gives error message while creating a user. 

### ISSUE THREAD

**Issue by rempargo** [fatfreecrm/fat_free_crm#412]
While creating a user and entering the e-mail address, and accidentally adding a space (which happens usually with copy-paste), you will get 'Email should look like an email address.'.

For some people, this can take a long time to figure out what is wrong.
![fatfreecrm](https://cloud.githubusercontent.com/assets/261394/5817470/81fe2266-a0ac-11e4-9230-1d4a8602371d.png)

Can the e-mail address be stripped from pre and post spaces, before checking and submitting?

**Comment by unijewski** [comment]
Hi, I think I've just fixed the problem. Before creating or editing an user we have to use `strip` method for the email field.
