### ISSUE TITLE
Custom field serialization is broken

### ISSUE THREAD

**Issue by steveyken** [fatfreecrm/fat_free_crm#415]
When a "checkbox list" custom field is added, we run serialization code to ensure ActiveRecord treats the data as an Array. This has stopped working in the rails4 branch.

Steps to reproduce
- Goto /admin/fields
- Add a new custom field of type "Checkbox list" (not checkbox) and give it several pipe separated values.
- Save the field
- Open up a rails console and type:
  
  Contact.serialized_attributes

The only result is `subscribed_users` but we should see the new custom field as well.

Relevant code is here https://github.com/fatfreecrm/fat_free_crm/blob/rails4/lib/fat_free_crm/fields.rb#L39

I've verified that `serialize(custom_field_name, Array)` is being called but appears to be making no difference to the serialized_attributes.

**Comment by steveyken** [comment]
Note: I'm getting a deprecation warning that suggests ```serialize``` is going away in Rails 5.0 with no replacement.

**Comment by warp** [comment]
When I create a checkbox array field it saves and loads fine so perhaps this is not really an issue?

**Comment by steveyken** [comment]
What happens when you save more than one value? I.e. check 2 of the three options?

**Comment by warp** [comment]
It appears to work fine

**Comment by steveyken** [comment]
Interesting... I'll check some more into this. I'm getting serialization problems on some custom plugins we use internally... using a Hash I think. I need to read more about what ```serialize``` is getting dumped out of Rails 5.0

**Comment by steveyken** [comment]
I've checked how this goes with the migration from rails 3.2 to rails 4.2 on stock FFCRM and it works fine... must be a problem with Hash in my custom plugin.

**Comment by steveyken** [comment]
More about serialization in Rails 5 here rails/rails#15704 and it's replacement: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attributes.rb

**Comment by CloCkWeRX** [comment]
There's some work I did here in the rails5 version bump; but I'm really unclear if I did the right changes. Are you able to grab master and test it; to see what the behaviour is?

**Comment by CloCkWeRX** [comment]
Well, going to cut the 0.15.0 release given it's had a few months of testing with rails 5. If this is wrong, we'll reopen.
