### ISSUE TITLE
Email dropbox duplicates

### ISSUE THREAD

**Issue by DmitriySalko** [fatfreecrm/fat_free_crm#416]
Hello

Email dropbox feature seems to show each email twice in CRM. We use GMail mailbox with IMAP access.

I've added "processed folder" too, but still the same.

Any suggestions?

Update: Looks like those duplicates appear only if you view Account, not Contact. So, I assume that it has nothing to do with IMAP itself.

**Comment by DmitriySalko** [comment]
Sorry everyone, it appears to be a "feature".

**Comment by steveyken** [comment]
The algorithm tries to match the email to the relevent entity in CRM but doesn't always get it entirely right. E.g. 'gmail.com' isn't really a great account to setup in the system. Are you finding that emails are linked to both accounts and contacts?

**Comment by DmitriySalko** [comment]
My problem was actually caused by this code

https://github.com/fatfreecrm/fat_free_crm/blob/master/lib/fat_free_crm/mail_processor/dropbox.rb#L182-L196

Once I figured out there is a setting, I was able to turn it off.

Thank you.
