### ISSUE TITLE
Accounts cannot discard (attach) Contacts or Opportunities 

### ISSUE THREAD

**Issue by beixingqiao** [fatfreecrm/fat_free_crm#417]
Hi friends, I am new user and I met some trouble, I dont known whether I do something wrong.
I want to attach some contacts to account,  I click the `Select Contact` ,fill the contact name, then press `Enter`, nothing happened. So I open 'FIrebug' to check what retrun, it says:
```
undefined method `name' for nil:NilClass
app/models/entities/account.rb:108:in `discard!'
app/controllers/entities_controller.rb:34:in `discard'
``` 
then, I place a `byebug` into `app/models/entities/account.rb`,line 108
```
  def discard!(attachment)
    if attachment.is_a?(Task)
      attachment.update_attribute(:asset, nil)
    else # Contacts, Opportunities
      byebug
      self.send(attachment.class.name.tableize).delete(attachment)
    end
  end
```
the procedure walk this statement will cause the error `self.send(attachment.class.name.tableize).delete(attachment)`, 
I dont how to correct,  anybody met this problem?
```
environment:
archlinux64
ruby 2.2.0
Rails 3.2.21
web server : unicorn
```
need more info , please comment, thanks!

**Comment by steveyken** [comment]
It seems to work ok for me. Have you made any code modifications to Fat Free CRM?

You can try it out here: http://master.fatfreecrm-fat-free-crm-1bbda9a74e1b4e1e2ffd.ttrcloud.com (login as username "aaron", password "aaron"

**Comment by beixingqiao** [comment]
Thank you for your help,@steveyken.yep, demo is OK. 
Em... I didn't modiffications any code.Just now, I attempt to remove the whole dir and database (mysql), and do a fresh setup.But the problem remain exist.I dont know how to find the problem. below I attach the setup step.
1. `git clone https://github.com/fatfreecrm/fat_free_crm.git`
2.  `cp settings.default.yml settings.yml`
3.  `bundle install`
4.  `rake db:create` , `rake ffcrm:setup` , and fill the username ,passwd,email.
5.  change `config/unicorn.rb`
```
working_directory "/home/hq/ruby/crm"
pid "/home/hq/ruby/crm" + "/tmp/unicorn.pid"
stderr_path "/home/hq/ruby/crm" + "/log/unicorn.log"
stdout_path "/home/hq/ruby/crm" + "/log/unicorn.log"
listen '/tmp/unicorn.crm.sock'
worker_processes 
```
6.`bundle exe unicorn -c config/unicorn.rb`

Then I login, everthing is OK but I just cant attach remain. What should I do ,thanks!

**Comment by beixingqiao** [comment]
addition:
Leads,Accounts,Contacts can attach (discard) task.

**Comment by beixingqiao** [comment]
`self.send(attachment.class.name.tableize).delete(attachment)`   Methods Added by has_many dont work, `self.send(attachment.class.name.tableize)` have no `size` `empty` `where` etc methods.

**Comment by beixingqiao** [comment]
maybe it is a bug in `activerecord`,I'll try another version `activerecord`.
https://github.com/activescaffold/active_scaffold/issues/380

**Comment by beixingqiao** [comment]
finally, I found the point.In file `activerecord-3.2.21/lib/active_record/associations/has_many_association.rb`  I change these few lines, and it works,
line 53, 57,61,80:
`reflection = reflection` change to `reflection = reflection()`
I think maybe ruby 2.2.0 update some syntax  :)

**Comment by ain** [comment]
With #419 the above-suggested ActiveRecord monkey-patching is not necessary. Please avoid changing ActiveRecord, it could have an impact in other implementations of the software.

**Comment by beixingqiao** [comment]
Thanks, I'll restore ActiveRecord  and checkout the new ffcrm.

**Comment by ain** [comment]
@beixingqiao make sure to come back with feedback please :)

**Comment by beixingqiao** [comment]
@ain,Yes, it works. thank you very much :+1:
