### ISSUE TITLE
bundle install --deployment fails.

### ISSUE THREAD

**Issue by cchavez** [fatfreecrm/fat_free_crm#421]
Hi All.

I'm on fedora 20 and the installation of the gems using the --deployment fails with the following message:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150217-22268-15y5y7v.rb extconf.rb 
creating Makefile
Compiling v8 for ia32
Using python 2.7.5
Using compiler: /usr/bin/c++ (GCC version 4.8.3)
/usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/gems/libv8-3.16.14.7/ext/libv8/builder.rb:28:in `make_flags': undefined method `include?' for nil:NilClass (NoMethodError)
        from /usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/gems/libv8-3.16.14.7/ext/libv8/builder.rb:56:in `block in build_libv8!'
        from /usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/gems/libv8-3.16.14.7/ext/libv8/builder.rb:49:in `chdir'
        from /usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/gems/libv8-3.16.14.7/ext/libv8/builder.rb:49:in `build_libv8!'
        from /usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/gems/libv8-3.16.14.7/ext/libv8/location.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/gems/libv8-3.16.14.7 for inspection.
Results logged to /usr/local/fat_free_crm/vendor/bundle/ruby/2.1.0/extensions/x86-linux/2.1.0/libv8-3.16.14.7/gem_make.out
An error occurred while installing libv8 (3.16.14.7), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.7'` succeeds before bundling.

I have installed v8, but not sure why it fails. Just doing : bundle install, the gems installation works.

Do anyone have get this error?

**Comment by mrIllo** [comment]
I had the same issues on Ubuntu 12.04.5 LTS.
This got libv8 installed:
gem install libv8 -v '3.16.14.7' -- --with-system-v8

**Comment by steveyken** [comment]
thanks @mrlllo that should work.
```libv8``` is a dependency for installing ```therubyracer``` @cchavez Check out https://github.com/cowboyd/libv8 for installation instructions if you aren't able to get the above working.

**Comment by cchavez** [comment]
Yes, that work for libv8, but I have another issue with therubyracer gems. It did not compile.

**Comment by steveyken** [comment]
If you have nodejs already installed. You can comment out 'gem
therubyracer' in Gemfile. ExecJS will pick up the node runtime instead.

**Comment by cchavez** [comment]
Right, I did that and now is working, thanks.
