### ISSUE TITLE
fatfreecrm.com website not working

### ISSUE THREAD

**Issue by rassom** [fatfreecrm/fat_free_crm#422]
Hi,

I can't get to the website fatfreecrm.com, nor does the demo subdomain (http://demo.fatfreecrm.com/) show any content. Tried both yesterday and today with different browsers with no luck.

Best,
Rasmus

**Comment by perlmunger** [comment]
Same here.

**Comment by steveyken** [comment]
Thanks for raising the issue. It's back up now and I've set up more robust monitoring, so hopefully I'll be the first to notice next time.
