### ISSUE TITLE
circular argument reference - reflection

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#428]
On startup the following warning is thrown 4 times (running MySQL):
```
/Users/ain/.rvm/gems/ruby-2.2.0/gems/activerecord-3.2.21/lib/active_record/associations/has_many_association.rb:53: warning: circular argument reference - reflection
```

**Comment by steveyken** [comment]
Not sure how compatible ruby 2.2 is with rails 3.2. We're about to push FFCRM rails 4 to master so this will hopefully go away.

**Comment by ain** [comment]
I don't recall having it a while ago on the same stack. Weird.

**Comment by ain** [comment]
Clearly not a FFCRM (dependencies) problem, having it on another completely unrelated project:
```
/Users/ain/.rvm/gems/ruby-2.2.0/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
```

**Comment by jooddang-nbt** [comment]
I can see the same problem on my side. 
Ruby 2.2.1, Rails 3.2.18. How is this problem solved?
