### ISSUE TITLE
ExecJS fails the deploy on jquery.coffee

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#429]
When deployed with Cap 3, ExecJS fails during asset compilation:
```
ExecJS::ProgramError: TypeError: Cannot set property 'root' of null
  (in /usr/share/rails/…/releases/20150226225353/vendor/assets/javascripts/chosen.jquery.coffee)
```
Platforms experienced on:
```
Mac OS X 10.10.2
Debian 7
```

**Comment by ain** [comment]
Workaround: install Node.js and disable [therubyracer](https://github.com/fatfreecrm/fat_free_crm/blob/master/Gemfile#L85) dependency.

**Comment by jianbo** [comment]
Having the same problem, I commented out the gem therubyracer, and added gem 'node', still doesn't work, any idea?
Thanks

**Comment by steveyken** [comment]
Execjs should generally find a js runtime on the system paths. Try removing
both 'gem node' and gem 'therubyracer', installing nodejs (ensure it's
available on the system paths) and try again?

**Comment by steveyken** [comment]
I think the issue is related to https://github.com/jashkenas/coffeescript/issues/3829 I'm going to peg the coffee-script-source gem to v1.8.x for now.
