### ISSUE TITLE
Using FatFreeCRM on staging env #rails4

### ISSUE THREAD

**Issue by voleoo** [fatfreecrm/fat_free_crm#431]
I installed FatFreeCRM as Rails engine and if i want to run
```
RAILS_ENV=staging rake assets:precompile
```
i have error 
```
NameError: uninitialized constant FatFreeCRM::Application
```

If i'm compiling assets for production env, i don't see this error and all is good
#rails4

**Comment by fkoessler** [comment]
Same error here, it's weird since fat_free_crm gem comes with the staging environment. (config/environments/staging.rb file is present)
Where should I be looking to fix this issue?

**Comment by steveyken** [comment]
Merged PR. Should be fixed
