### ISSUE TITLE
New Feature Request: Import from csv, excel, or pst files

### ISSUE THREAD

**Issue by jzdechlik** [fatfreecrm/fat_free_crm#433]
Hi, 
I am interested in using your application, but have no clue as to how to import my 3500 records from MS Exchange / Outlook.

Has someone already written a module for this?  It seems tricky to import them directly into the database engine.

Any help is appreciated.  Thanks in advance!

**Comment by steveyken** [comment]
You could have a look at https://github.com/orbitalimpact/Fat-Free-CRM-Lead-Importer It's a few years old but might give you some insights into what is required to get an import working.
