### ISSUE TITLE
Status of devise?

### ISSUE THREAD

**Issue by chriscarpenter12** [fatfreecrm/fat_free_crm#439]
What is the status of getting Devise integrated into fat free? I see there is an open pull request and two branches mentioning devise.

**Comment by steveyken** [comment]
I'm pretty keen to get it merged in but can't find the time at the moment. We've also upgraded to rails 4 in the meantime so the PR will need adjusting and re-basing.

**Comment by chriscarpenter12** [comment]
Thanks for the quick update. I was looking into using fat free for an upcoming project and was curious of the devise status.
