### ISSUE TITLE
Contacts and Opportunities do not load the entire list of existing accounts

### ISSUE THREAD

**Issue by matthewmalone** [fatfreecrm/fat_free_crm#441]
When you load information manually into the accounts table using PHPMyAdmin, the Contacts and Opportunities pages do not load the entire list of existing accounts (it only loads the number of accounts that were in the accounts table before the manual load)

Or am I missing something? Is there a counter for the number of active accounts?

**Comment by steveyken** [comment]
There shouldn't be a counter for accounts data. (We use counters for leads
and opportunities (e.g.
https://github.com/fatfreecrm/fat_free_crm/blob/master/app/models/entities/opportunity.rb#L86
)

When you loaded the accounts data, did you also load accounts_opportunities
and accounts_contacts join data? This will created the individual
relationships between an account and it's contact or opportunity.

See
*
https://github.com/fatfreecrm/fat_free_crm/blob/master/app/models/entities/account_contact.rb
*
https://github.com/fatfreecrm/fat_free_crm/blob/master/app/models/entities/account_opportunity.rb

Regards,
Steve

**Comment by johnnyshields** [comment]
@steveyken can this be closed?

**Comment by steveyken** [comment]
yup!
