### ISSUE TITLE
Update Dockerfile to use Docker Compose, add instructions

### ISSUE THREAD

**Issue by bluepuma77** [fatfreecrm/fat_free_crm#444]
I would love to test Fat Free CRM, but I am a newbie to Rails. Docker could be a solution for this, to enable a simple install and test of Fat Free CRM.

Currently a Dockerfile exists, but it seems to use fig, which is deprecated: "Fig has been replaced by Docker Compose, and is now deprecated. The new documentation is on the Docker website."

It would be great to have an updated Dockerfile to use current Docker Compose and the Docker installation instructions added to https://github.com/fatfreecrm/fat_free_crm.

**Comment by bluepuma77** [comment]
Here is a simple Dockerfile to test-drive Fat Free CRM with SQLite, place it in an empty directory
```
FROM rails

RUN apt-get update && apt-get install -y libmagick++-dev
RUN git clone http://github.com/fatfreecrm/fat_free_crm.git

WORKDIR /fat_free_crm

# use file-based SQLite database - this may be slow and unreliable
RUN cp config/database.sqlite.yml config/database.yml
RUN gem install sqlite3

# install dependencies
RUN bundle install
RUN rake db:create
RUN rake db:migrate

EXPOSE 3000

# start server and bind to all IPs in docker container
ENTRYPOINT ["rails", "server", "--binding=0.0.0.0", "--port=3000"]

# for interactive setup use this command in shell
#   rake ffcrm:setup
# create demo data in database
#RUN rake ffcrm:demo:load
# create admin user with given user/pass
#RUN rake ffcrm:setup:admin USERNAME=admin PASSWORD=password EMAIL=admin@example.com
```
Build the Docker image
```
sudo docker build -t ffcrm .
```
Start the Docker container
```
sudo docker run --name my-ffcrm -p 8080:3000 -d ffcrm
```
Connect to the container shell and create demo data and/or admin user (this can be done via Dockerfile)
```
$ sudo docker exec -it my-ffcrm bash
# rake ffcrm:demo:load
# rake ffcrm:setup:admin USERNAME=admin PASSWORD=password EMAIL=admin@example.com
```
Now you can login with your browser at http://server:8080 with admin/password

**Comment by johnnyshields** [comment]
Closing this as we have a Dockerfile now.
