### ISSUE TITLE
Mixed Content:  This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by claudia-pfeil** [fatfreecrm/fat_free_crm#445]
Hello,

after SSL certification we get this error message on the edit-ajax calls in the list views of leads, accounts and contacts:

Mixed Content: The page at 'https://.../leads' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://.../leads/57/edit?previous=null'. This request has been blocked; the content must be served over HTTPS.

Can you tell me where exactly can I change the protocol type to https of the ajax request,please?

Thank you.

**Comment by claudia-pfeil** [comment]
I have found it on the nginx configuration on the server: /etc/nginx/sites_availables/<app>_config and than turn line proxy_set_header X-Forwarded-Proto http into proxy_set_header X-Forwarded-Proto https, voila!

**Comment by steveyken** [comment]
Good to know, thanks!

**Comment by maxpalermo** [comment]
you can also add this directive in .htaccess root file

RewriteEngine on
RewriteCond %{REQUEST_SCHEME} =http
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

to force redirect on https protocol.
