### ISSUE TITLE
String#snakecase in ffcrm core_ext breaks String#snakecase in Savon/Wasabi

### ISSUE THREAD

**Issue by kukareka** [fatfreecrm/fat_free_crm#447]
`String#snakecase` extension in `lib/fat_free_crm/core_ext/string.rb` is used in ffcrm  `app/views/tasks/_edit.html.haml` to convert strings like 'This week' to 'this_week'.

Unfortunately, it does not convert CamelCase strings to snake_case and therefore overwrites and breaks `String#snakecase` in Savonrb/Wasabi gem (https://github.com/savonrb/wasabi/blob/master/lib/wasabi/core_ext/string.rb).

**Comment by rennhak** [comment]
Seems like one form of project 'monkeypatching' is conflicting with another project's 'monkeypatching', namespace pollution all the way.

**Comment by kukareka** [comment]
Reference savonrb/wasabi#59.

**Comment by tjarratt** [comment]
@rennhak I totally agree. I just pushed out a new version of Wasabi that does not rely on this monkey patch, so I think we should be good to close this.

**Comment by tjarratt** [comment]
Although Savon also monkeypatches `String` as well to provide `#snakecase`. Unsure if that's going to cause a problem for you@ kukareka.

**Comment by steveyken** [comment]
Thanks for picking up on this. Keen to remove the namespace pollution. As a minimum, I think FFCRM should be using the rails ```underscore``` method instead of ```downcase``` here https://github.com/fatfreecrm/fat_free_crm/blob/master/lib/fat_free_crm/core_ext/string.rb#L26

Ideally, most of this core_ext string module could be refactored out and not override the String class.

**Comment by steveyken** [comment]
There was only one place using ```snakecase``` in FFCRM codebase and that could has been refactored to no longer use it. I've removed ```String#snakecase``` from FFCRM in this commit 8fc109d so hopefullly no more namespace clashing.

**Comment by rennhak** [comment]
Thank you everyone for helping improve and fix the situation. Greatly appreciated !
