### ISSUE TITLE
Can someone please explain me the right way to use stylesheet_includes ?

### ISSUE THREAD

**Issue by yhourdel** [fatfreecrm/fat_free_crm#458]
Hi,

I've managed to use all hooks, except this one. I've tried multiple ways, nothing works.
I'm guessing this is due the to `yield` that is inside its block, but I don't get it.
Can you tell me what's wrong with this, for example ?

```
class ApplicationCallback < FatFreeCRM::Callback::Base
  def stylesheet_includes(view, context = {})
    view.stylesheet_link_tag('mystyle')
  end
end
```

Thanks a lot

Yann

**Comment by johnnyshields** [comment]
Closing unless you still need help with this.
