### ISSUE TITLE
Tag links do not work for multiword tags

### ISSUE THREAD

**Issue by chrisgherbert** [fatfreecrm/fat_free_crm#460]
The tag links that appear in lists of resources do not work when the tag contains multiple words.

![screen shot 2015-09-16 at 6 52 59 pm](https://cloud.githubusercontent.com/assets/2541849/9920697/66db3a3c-5ca4-11e5-8767-429bb21d11d5.png)

![screen shot 2015-09-16 at 6 53 04 pm](https://cloud.githubusercontent.com/assets/2541849/9920701/6acaf31c-5ca4-11e5-8c89-29e01464b89e.png)

**Comment by johnbumgardner** [comment]
some applications use #multiword tag# to achieve this.

Would this be an acceptable feature to add? @johnnyshields

**Comment by johnbumgardner** [comment]
@johnnyshields this issue fix was merged in
