### ISSUE TITLE
Mobile usage - responsive behaviour

### ISSUE THREAD

**Issue by rowalth** [fatfreecrm/fat_free_crm#465]
Are there any plans or initiatives to make ffcrm accessible via mobile device?

**Comment by steveyken** [comment]
I would dearly love to see this happen. It's just a matter of time and effort. I'm not able to put much time into FFCRM development at the moment, but welcome PRs and others getting involved.

**Comment by imkarthikk** [comment]
I've just started working on this. But the progress is going to be a little slow. I love the project so much and I want to integrate material design into it. :) Let me know your comments.

**Comment by lixonic** [comment]
@steveyken @imkarthikk i started tweaking it yesterday, but got stuck at simple_forms and jumpboxes. so i'm thinking to create mobile first template in bootstrap and then making views. 
![fat free crm 1](https://cloud.githubusercontent.com/assets/934220/15319988/a2f71f2e-1c4b-11e6-9cd0-f6f49415ab7d.png)
![fat free crm2](https://cloud.githubusercontent.com/assets/934220/15319992/a96042d2-1c4b-11e6-9ed1-dd97604fc42b.png)

**Comment by imkarthikk** [comment]
Makes sense. I can help you out with that. Lemme know. 

Sent from my iPhone
Smart businesses run SHRINK. Do you?

**Comment by steveyken** [comment]
Encouraging to see work on this. Appreciate the effort people are
undertaking.

There's a lot of things about the architecture of FFCRM that make it hard
to skin better (not using unobtrusive javascript for example). That said,
there is a real end-user need to skin and get this working on mobile. I'd
certainly use it!

There is also another thread with panigrah on the google lists about using
AdminLTE skin which I believe is also mobile friendly.
https://groups.google.com/forum/#!topic/fat-free-crm-users/VM3NAKEQgow I'd
make the same comments on there as I am here.

Personally, I'm unable to support with work effort right now, though I'd be
open to merging pull-requests when things are ready.

I will also be taking a break until end of June so will be unresponsive on
email during that time.

I guess my vibe is this: highly supportive of your mobile efforts, low
expectation to be able to assist myself.

Regards and thanks for reaching out,

Steve

**Comment by lixonic** [comment]
AdminLTE skin is so beautiful and i believe it would kill the user experience as it changes the whole ui . wdyt?

@imkarthikk i'll ping you when i'm done.  😃

**Comment by rocknrollMarc** [comment]
Yap I would join in on that maybe we can use bootstrap and make it look a bit more modern full stop.

**Comment by Abdenasser** [comment]
Hi guys, any updates on this ??

**Comment by johnnyshields** [comment]
@CloCkWeRX I think this is a reasonable request, it would certainly help my sales guys. IMHO we should look at stripping out the current CSS and replacing with Bootstrap 4.

**Comment by imkarthikk** [comment]
@johnnyshields I agree. Bootstrap 4 is super good, and we can try to bring in a light-weight Gulp support as well, to see if we can process SAAS or SCSS better with FatFree's backend. I stopped working on it for sometime, to focus on my job. But I have some free time now to take this up.

**Comment by zekedran** [comment]
@johnnyshields +1; It's definitely worth rewriting API only backend and having a react redux frontend. We can choose Vue, but we can easily port react to react native for mobile apps at a later stage. I'm not so familiar with Vue, is there any such possibility in Vue as well?

**Comment by johnnyshields** [comment]
Looking objectively React is much more popular in terms of jobs and number of developers, and it's the gold standard of JS frameworks. I don't see any reason why React can't work well with Rails--especially MobX (instead of Redux) seems to work pretty well.

![image](https://user-images.githubusercontent.com/27655/45607628-aae12300-ba88-11e8-9bd8-853430ea3668.png)

https://medium.com/@TechMagic/reactjs-vs-angular5-vs-vue-js-what-to-choose-in-2018-b91e028fa91d

**Comment by WMPayne** [comment]
I have a larger production site using React, and experience using React Native and Vue as well. I would certainly go with Vue for new projects. Although you're right, that many jobs and current projects use React (I do), I quit using it for new development. Ultimately, it's up to you. 

Porting to React Native is not nearly as straightforward as it might seem, by the way, since it's not absolutely portable. Yes, you can reuse components and such, but it's unlikely you'll get much value out of it (at least, when I've done it, it wasn't super helpful).

Regardless, API backend is definitely a good idea.

**Comment by johnnyshields** [comment]
I'm the CTO of company with 20 devs and to be honest I've gotten deeply involved in any frontend framework. We use Ember JS and have been switching for React. My only concern for open-source projects like this is ease of other community members to getting involved, and for that React seems like a clear winner that isn't going away anytime soon. (Ember JS for example is a dying breed...)

**Comment by WMPayne** [comment]
Makes sense. React definitely isn't going to die out any time soon. 

That being said, having an "API only" backend would allow for multiple front-ends if people wanted to develop for a different front end or a custom solution (easier integration with some other front end they have or similar).

**Comment by stanleylhs** [comment]
Sorry for the prolonged inactivity. Last time (years ago) when I talked with @steveyken it seems that we do have a old API backend already in place? Or are those code gone? I need to check the codebase again to see what we have.

I would be definitely up for a Vue/React rewrite. I have connections with the Hong Kong Vue.js meetup group, might be able to recruit for more volunteers to join this project if we decide to side with Vue.

**Comment by WMPayne** [comment]
I don't have any experience with this, but apparently NativeScript exists for using various JS frameworks (including Vue) that might be another factor if porting to mobile apps is important: https://www.nativescript.org/

**Comment by adamlfoater** [comment]
Hi all, I came across this crm and am looking for developers who can help me customise a version for my own needs. Can anyone help whilst at the same time improving FatFreecrm for others?

**Comment by CloCkWeRX** [comment]
I've raised some more specific cards around an incremental migration to bootstrap #913 #914 #912 #911 

Ideally, this gives the bare minimum mobile UX of appropriate font sizes and focus on the relevant entity, lists, etc.

For now, I'm keeping the scope as small as possible, so we can do a small slice at a time - so React or a similar framework is probably out of the equation for the short term.
Hopefully the end result is something mostly workable on mobile, with a few rough edges; and if we do decide to refactor to something more SPA like the barriers are lower to take an isolated section and migrate it.
