### ISSUE TITLE
C:/RailsInstaller/fat_free_crm/config/environment.rb:10:in `<top (required)>' Tasks: TOP => ffcrm:setup => environment

### ISSUE THREAD

**Issue by MikeCav0524** [fatfreecrm/fat_free_crm#466]
C:/RailsInstaller/fat_free_crm/config/environment.rb:10:in `<top (required)>'
Tasks: TOP => ffcrm:setup => environment
(See full trace by running task with --trace)

C:\RailsInstaller\fat_free_crm>

**Comment by stanleylhs** [comment]
Hi @MikeCav0524, are you still trying to install it on Windows?

If so please provide more debug trace for us to help you in a new issue.

I will close this one for now.
