### ISSUE TITLE
PROBLEM INSTALLING ON WINDOWS XP VM sp3 

### ISSUE THREAD

**Issue by MikeCav0524** [fatfreecrm/fat_free_crm#467]

**Comment by MikeCav0524** [comment]
C:\RailsInstaller\fat_free_crm>rake ffcrm:setup RAILS_ENV=production
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
NoMethodError: undefined method `initialize!' for :Application:Symbol
C:/RailsInstaller/fat_free_crm/config/environment.rb:10:in `<top (required)>'
Tasks: TOP => ffcrm:setup => environment
(See full trace by running task with --trace)

C:\RailsInstaller\fat_free_crm>

**Comment by MikeCav0524** [comment]
NOW I GET THIS ONE 
C:\RailsInstaller\fat_free_crm>rake ffcrm:setup RAILS_ENV=production
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th
is error.
<internal:prelude>:10:in `synchronize'
C:/RailsInstaller/fat_free_crm/config/environment.rb:10:in `<top (required)>'
Tasks: TOP => ffcrm:setup => environment
(See full trace by running task with --trace)

**Comment by steveyken** [comment]
Do you want to try running the rake task with the '--trace' command - this
will help pin point the error a bit more. Could also add the bundle exec
prefix to set the gem environment. Try this:

    bundle exec rake --trace ffcrm:setup RAILS_ENV=production

The other option is to try the 'all in one' bitnami installers -
https://bitnami.com/stack/fat-free-crm/installer#windows

Regards,
Steve

p.s. just noting your database.yml mysql password for this setup is visible
in the email dump above... would recommend changing it :)
