### ISSUE TITLE
An error occurred while installing with OS X

### ISSUE THREAD

**Issue by gabrielbrunette** [fatfreecrm/fat_free_crm#472]
I am having issues installing it.

An error occurred while installing pg (0.18.3), and Bundler cannot continue.

**Comment by thalessr** [comment]
@gabrielbrunette Have you installed the postgresql in your machine?  If not, install it using homebrew
`brew update && brew install postgresql`
And then `gem install pg` or `bundle install`
I hope it works for you.

**Comment by gabrielbrunette** [comment]
Thank you very much. Now it works perfectly. I am new at this and still trying to figure out how can I add a new user. If you could stir me in the right direction I would appreciate it very much.

**Comment by steveyken** [comment]
Thanks @thalessr Updated https://github.com/fatfreecrm/fat_free_crm/wiki/Setup-Linux-or-Mac-OS also.
