### ISSUE TITLE
cannot create the database "rake db:create RAILS_ENV=production"

### ISSUE THREAD

**Issue by aymangithub** [fatfreecrm/fat_free_crm#473]
when i going to create DB with 
rake db:create RAILS_ENV=production
it takes a while and not responding for many hours.
when i exit with (control+C) in keyboard 
it give me this error:
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=> "fat_free_crm_production", "pool"=>5, "username"=>"root", "password"=>"root", "socket"=> "temp/mysql.sock", "host"=>"localhost"}
notes:
1:
the settings in the database.yml file is 
development: &development
     adapter: mysql2
     encoding: utf8
     database: crm_production
     pool: 5
     username: root
     password: root
     socket: /tmp/mysql.sock
     host: localhost

2: i working on windows 10

**Comment by steveyken** [comment]
Have you set up Mysql for Windows. You will need to edit config/database.yml with the appropriate connection information before being able to create a database. See https://github.com/fatfreecrm/fat_free_crm/blob/master/config/database.mysql.yml.
