### ISSUE TITLE
Need help accessing the login page.

### ISSUE THREAD

**Issue by gabrielbrunette** [fatfreecrm/fat_free_crm#475]
Hi,

Could you please explain how I can log in to fat_free_crm after installing it on my server. I just installed it on hostgator using Filezila. How do I find the login page. Using the same logic I use when I install a new html page, the logical solutions would be: mywebsite.com/fat_free_crm/login but it is not working. 

Sorry for the inconvenienve & thanks for your help.

Gabriel

**Comment by steveyken** [comment]
The login page is '/login' e.g. http://demo.fatfreecrm.com/login

Perhaps you may need to set up a virtual machine host or rewrite rules with hostgator but you should consult their support documentation for specifics.
