### ISSUE TITLE
FFCRM at the Franchise Level?

### ISSUE THREAD

**Issue by perlmunger** [fatfreecrm/fat_free_crm#476]
I don't really see any way to use FFCRM out of the box at a higher level for a franchise, but I figured I would ask. If you were to customize the system to work where users, when they log in, only see data for their franchise, would that be a fundamental change or is there a way to customize? I could add entities higher up in the hierarchy by creating new models (e.g. franchise has many franchisees has many users, etc.), but I was hoping there may be a way of accomplishing the same without a fundamental architectural change.

I realize you could just stand up an instance for each franchisee, but this design would be pretty cumbersome to navigate from the highest admin level. It is preferable to be able to login at the top level and drill down to each franchisees' specific activity as super admin, but only be able to login and see your calendar if you are a technician, for example.

Any thoughts on this would be welcome and appreciated.

Thanks.

**Comment by johnnyshields** [comment]
@perlmunger The way FFCRM is architected it is a single-tenant app. It can't be used as a multi-tennant service at the moment. You might be able to achieve what you want via User Groups. I think this issue can be closed as it is not on the immediate roadmap to change the fundamental structure (such a change would affect every object in the DB.)

**Comment by johnnyshields** [comment]
Closing as this is not in scope in the immediate future.
