### ISSUE TITLE
oauth2_google plugin dependency failure on latest ffcrm ... is there any other auth option?

### ISSUE THREAD

**Issue by cypa** [fatfreecrm/fat_free_crm#478]
CRM itself is brilliant, but we need SSO auth, but oauth2_google plugin seems not installable out of the box for latest ffcrm

```
Resolving dependencies........
Bundler could not find compatible versions for gem "acts_as_commentable":
  In snapshot (Gemfile.lock):
    acts_as_commentable (= 4.0.2)

  In Gemfile:
    acts_as_commentable

    ffcrm_google_oauth2 was resolved to 0.0.2, which depends on
      fat_free_crm was resolved to 0.11.0, which depends on
        acts_as_commentable (~> 3.0.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by panigrah** [comment]
download a local copy of ffcrm_google_oauth2 into a separate folder. update ffcrm_google_oauth2.spec and delete/comment out the line `s.add_dependency "fat_free_crm"`. in your fatfreecrm Gemfile refer back to your local copy of the gem and run `bundle update`

**Comment by johnnyshields** [comment]
@cypa can you confirm this workaround resolves the issue? Note that we will soon update from Authlogic to Devise soon and working with Oauth2  may be easier then.
