### ISSUE TITLE
Devise: Use email as login to log into FFCRM

### ISSUE THREAD

**Issue by cypa** [fatfreecrm/fat_free_crm#479]
as not everybody like or remember login name itself ... and no external auth, like oauth, possible by now

**Comment by yrck** [comment]
You can use an email address in the username field. 

I added a validation to my install to make sure an email is used. It seems redundant but Salesforce sets up this way too.

**Comment by johnnyshields** [comment]
This issue should be closed

**Comment by johnnyshields** [comment]
In the current state I do not think you can login with email. My Devise PR will support this.

**Comment by johnnyshields** [comment]
This will be handled in the Devise PR so I'm closing the issue for now.
