### ISSUE TITLE
Can not select or add tags

### ISSUE THREAD

**Issue by zeroone** [fatfreecrm/fat_free_crm#480]
after "Tag:", not show add tag textbox, and there is an error in console: "Uncaught Error: No select2/compat/inputData".

I did some search about this error, someone said that "When using select2 with x-editable, the full version (select2.full.js) is required.".

Is there anybody get the same error? How can I fix it?

**Comment by steveyken** [comment]
Looks like we need to update the `select2-rails` ruby gem to v4.0.1

ref: https://github.com/argerim/select2-rails/pull/143

**Comment by steveyken** [comment]
Just waiting for a new gem release of select2-rails which has this fix.

**Comment by zeroone** [comment]
select2-rails already release [v4.0.1](https://rubygems.org/gems/select2-rails/versions/4.0.1), but it still not contain select2.full.js.
And I manually add select2.full.js to code, the textbox show up, but still not work.
Finally I back to v3.5.9.3, it works.
Thank you.

**Comment by steveyken** [comment]
OK thanks, I might revert to v3.5.9.3 then!

**Comment by steveyken** [comment]
Committed 312d7f1 to master

**Comment by steveyken** [comment]
if v3.5.10 doesn't work, I'll try v3.5.9.3

**Comment by zeroone** [comment]
ok, thanks a lot!

**Comment by steveyken** [comment]
v3.5.10 still gives console error. Reverting to v3.5.9.3 and we'll fix the underlying issue in the future.

**Comment by stanleylhs** [comment]
I assume PR #327 will fix this, right???

**Comment by clawster** [comment]
I found a solution to the js error msg here... https://github.com/select2/select2/issues/4064

Using select2-rails 4.0.3

app/assets/javascripts/application.js.erb
@@ -8,7 +8,7 @@
-//= require select2
+//= require select2-full

This got rid of the warning... But...

1) The Search feature in the textbox still does not work. Although the "select2_tag" hidden input is populated with the tags when i look at the html-source.

2) Entering a new "Tag" as described in the tooltip ("Select some tags, or create a new tag by pressing 'enter'.") does not work either. It does not seem to trigger a request to the server.

Any suggestions?

**Comment by CloCkWeRX** [comment]
https://github.com/argerim/select2-rails#include-select2-rails-stylesheet-assets perhaps?

**Comment by CloCkWeRX** [comment]
https://select2.github.io/announcements-4.0.html#migrating-from-select2-35

**Comment by CloCkWeRX** [comment]
@clawster - did you want to have a go following the upgrade steps talked about in the link above; and perhaps shoot in a pull request?

**Comment by CloCkWeRX** [comment]
If anyone wanted to grab current master and test it further, it would be much appreciated
