### ISSUE TITLE
Add import plugin to installed app

### ISSUE THREAD

**Issue by georgTW** [fatfreecrm/fat_free_crm#486]
I installed fat free crm following this guide: 
http://guides.fatfreecrm.com/Setup-Linux-or-Mac-OS.html

Now I'd like to add a plugin (https://github.com/orbitalimpact/Fat-Free-CRM-Lead-Importer).
I know this plugin is broken with rails4, so I'd like to get it to work again.

I tested adding a plugin (add gem to Gemfile) with https://github.com/fatfreecrm/ffcrm_mingle
I get the following error:
````
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 4.2.0)

    ffcrm_mingle was resolved to 1.0.1, which depends on
      fat_free_crm was resolved to 0.11.0, which depends on
        rails (~> 3.2.2)
````
The same error pops up using the Importer plugin. It always resolves to version 0.11.0 ? Even though in https://github.com/orbitalimpact/Fat-Free-CRM-Lead-Importer/blob/master/Gemfile.lock#L5 we use a newer version? (I ran ````bundle update```` to even lift the version to 0.14.0)

Can anybody support? Probably provide a plugin that currently is working? So I can adapt the necessary changes..

Is there any other working csv-import plugin right now?

**Comment by georgTW** [comment]
Status update:
I got a working version with just removing the dependency for fatfreecrm.

Now since the database structure is different, addresses are not saved, I'm working on this..

Is there a nice function to check for doublets ?

**Comment by steveyken** [comment]
I think you would need to fork FFCRM Lead importer and hack the code to get
it working. Start with the ffcrm_import_leads.gemspec file and remove the
rails 3 constraint and run bundle update again... this should get you a bit
further.

https://github.com/orbitalimpact/Fat-Free-CRM-Lead-Importer/blob/master/ffcrm_import_leads.gemspec

Regards,
Steve

**Comment by georgTW** [comment]
I think you didn't properly read my update post. I'd like to leave this open to track my progress for others that are interested.

Also regarding my question: Does FFCRM have a funtion to test for douplets when creating a new contact?

**Comment by steveyken** [comment]
Apologies, you're right, I didn't respond to the updated comment. At the moment, there isn't an option to take for duplicate contacts built in to FFCRM however it's possible to create a plugin to do so. A "duplicate" contact can have different meanings in different systems depending on it's use. For example, if first name and last name are the same, is the contact a duplicate? Or should we check phone number or email instead so this is left to the implementor to decide.

**Comment by georgTW** [comment]
No worries ;)

Yeah, I was going to implement it like: first name, last name, email, phone the same --> duplicate

It's simply to avoid getting duplicates, when using the import function. So can I need to check the database with the plugin?

Next on the list: The addresses were moved to the ````addresses```` table and linked with the user id. 
Now when I try to save them: https://github.com/georgTW/Fat-Free-CRM-Lead-Importer/blob/master/app/models/import_lead.rb#L33-L35 it's not properly linked.
Can you point me in the right direction?

**Comment by steveyken** [comment]
Address is polymorphic - try setting addressable_type (in line 34) as well.
See app/models/address.rb for the types you can use

**Comment by georgTW** [comment]
I get the following error message using 
````
address = Address.new(:street1 => street, :city => city, :zipcode => zipcode, :country => country, :addressable_id => lead.id)
address.addressable_type = 'Billing'
address.save!
````

Error:
````
NameError in Admin::ImportLeadsController#create
uninitialized constant Billing
````

**Comment by steveyken** [comment]
Try Address.new(:street1 => street, :city => city, :zipcode =>
zipcode, :country => country, :addressable_id => lead.id,
:addressable_type => "Billing")

Does that work?

**Comment by georgTW** [comment]
> Does that work?

No :( But I figured it out: ````addressable_type = 'Lead'```` is the right value and we also have to set ````address_type = 'Business'```` Now the import works!

So now we need to check for duplicates and the addon is working again! Thanks for your help!

**Comment by georgTW** [comment]
In my latests commit we added a check for duplicates as well
