### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by panigrah** [fatfreecrm/fat_free_crm#487]
I forked a branch to work on moving ffcrm to rails5. There are a few unsupported gems that I had to take out. The entities are not rendering on the webpages due to an error with ransack_ui. This was to understand what it would take to move to rails5. Uses rails-5.0.0.beta3. 

1000 tests pass and 600 fail. Will continue working on it slowly.

If you would like to fork and start testing - see here.
https://github.com/panigrah/fat_free_crm/tree/rails5

**Comment by JorgeDDW** [comment]
How is it going your development ?

**Comment by panigrah** [comment]
Ready towards GA. some tests still fail - and I will push the latest into this branch later this week.

**Comment by panigrah** [comment]
All tests pass on rails5. Fork is here https://github.com/triloch/fat_free_crm

**Comment by JorgeDDW** [comment]
@panigrah Great news!!
Im already downloaded and when im trying to do a bundle install I get this: 
'''The path `/Users/Jorge/Desktop/projects/sass-rails` does not exist.''' 
How can i fix this?

**Comment by JorgeDDW** [comment]
``

**Comment by panigrah** [comment]
Download sass-rails gem to your projects folder from github. Replace the files in sass-rails with the files from fat_free_crm/sandbox/sass-rails.

And continue.

Later today I will create a fork of sass-rails in github for use so you can skip the step above.

On Mon, Sep 26, 2016 at 4:38 AM, Jorge Dominguez < notifications@github.com [notifications@github.com] > wrote:
@panigrah [https://github.com/panigrah] Great news!!
Im already downloaded and when im trying to do a bundle install I get this:
'''The path /Users/Jorge/Desktop/projects/sass-rails does not exist.'''
How can i fix this?

**Comment by kirantpatil** [comment]
@panigrah, any update on supporting Rails 5 ?
