### ISSUE TITLE
Minor issue: login page looses focus

### ISSUE THREAD

**Issue by georgTW** [fatfreecrm/fat_free_crm#488]
When clicking on 'about' on the login page, the page will loose focus and the only way to come back is to press "Esc"

![image](https://cloud.githubusercontent.com/assets/18528524/14812777/3c6034ba-0bd1-11e6-8d91-67bcf6cdc58a.png)

Tested with latest fatfreecrm.

**Comment by georgTW** [comment]
Adding ````z-index:1```` to the box brings it into focus.
Also removing the margin from ````.ui-dialog-titlebar-close span {}```` fixes the blue 'x'

![image](https://cloud.githubusercontent.com/assets/18528524/14813631/2a1f73fc-0bd5-11e6-824d-a827bb033c56.png)

I'm not quite sure how to make a PR, also I only tested on Google Chrome 49

**Comment by steveyken** [comment]
Thanks! If you've pushed the code up to github somewhere, can you reply
with the link and we can assist with the PR?

Regards,
Steve

**Comment by georgTW** [comment]
Hi @steveyken I know how to make a pull request. But I don't know where to find those values in the code. I just edited them in chrome development.

I'm not really experienced with ruby :(

**Comment by steveyken** [comment]
Understood. Thanks for replying. Will keep this ticket open so we can make
the changes ourselves.
