### ISSUE TITLE
Pagination stops working after filter is applied

### ISSUE THREAD

**Issue by adisos** [fatfreecrm/fat_free_crm#497]
**Steps to reproduce**:
1. Open [demo](http://demo.fatfreecrm.com)
2. Go to `Leads` page
3. Uncheck one checkbox from sidebar
4. Click pagination link.

**Expected Results**
Entities should be changed

**Actual Results**
Nothing happening.

**Why this is happenning**
I think because `filter` action is available only through `POST` method, if we add new line to `routes` it should fix this. For example:
```
resources :leads, id: /\d+/ do
    collection do
      post :filter
      get :filter
      get :redraw
    end
  end
```

But I don't know, may be there are other ways to fix this. That's why I opened this ticket, instead of creating PR.

**Comment by stanleylhs** [comment]
@adisos This issue should be fixed!

I think we can close this thread.
