### ISSUE TITLE
Upgrade authlogic to 3.5+ - scrypt 2.0.2 dependency does not compile on ARM

### ISSUE THREAD

**Issue by thepaperescape** [fatfreecrm/fat_free_crm#500]
scrypt 2.0.2 dependency does not compile on ARM, however, it has been updated to successfully compile on ARM (https://github.com/pbhogan/scrypt/issues/23).

Please update dependency! Maintainer of scrypt says "there is no functional difference between v2 and v3 except that it runs on ARM."

**Comment by CloCkWeRX** [comment]
So, this one is dependent on authlogic 3.5, which currently breaks tests - a28131c32ac54ef7ea3a8612cedc188f6d6da0ff is where I tried it out.

**Comment by CloCkWeRX** [comment]
See also #520

**Comment by CloCkWeRX** [comment]
Fixed in 80d6e243913dbebd6660cc282a7553b2f045a857 2fca8a810f6cced031b255ecf55cb9a953bc184e 6f5248bc50475162f1b03171097c80939f9d0212 as part of the rails 5 work
