### ISSUE TITLE
fail to Bundle Install

### ISSUE THREAD

**Issue by JorgeDDW** [fatfreecrm/fat_free_crm#503]
Hi there people,

this is what I'm facing:

```
An error occurred while installing libv8 (3.16.14.13), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.13'` succeeds before bundling.

```

How can i fix this?

**Comment by stanleylhs** [comment]
Hi @JorgeDDW, are you installing on OSX?

If so, please read this thread about using the system v8 that comes with OSX.

**Comment by stanleylhs** [comment]
@JorgeDDW, I believe that you now have resolved your issue? I will close this issue then.

**Comment by papilip** [comment]
Hi, i propose for OSX `gem install libv8 -v '3.16.14.15'` the last version !
I must update for FreeBSD install !

**Comment by CloCkWeRX** [comment]
I forked this project (https://travis-ci.org/reduced-fat-crm/fat_free_crm) and this should be available in https://rubygems.org/gems/reduced_fat_crm/versions/0.14.0 - can you give it a go and see if that sorts out your issue?

**Comment by CloCkWeRX** [comment]
ea0ac63
