### ISSUE TITLE
Invalid username and password

### ISSUE THREAD

**Issue by tomordonez** [fatfreecrm/fat_free_crm#520]
ruby 2.3.1p112
Rails 4.2.7.1
OSX El Capitan

Using SQLite3

Went through the installation process as shown on the official doc.

Installed the default admin user like this:

`rake ffcrm:setup:admin USERNAME=admin PASSWORD=password EMAIL=admin@example.com`

Running the server in the login. I get the "Invalid username and password".

Went to the console. The user is in the database. Changed the password. Login and "invalid username and password".

What am I missing?

**Comment by patakijv** [comment]
+1 Same here... 

Using rails 4.2.7 
Using fat_free_crm 0.14.0
Ruby version: 2.3.1

Ran through the steps as guide suggested, used defaults for admin username and password but it won't authenticate successfully.

I also tried changing password in console and still get the invalid login response.

**Comment by patakijv** [comment]
As an update for this, I discovered if I changed the gemspec Gemfile.lock file for the **authlogic** gem so instead of ">=3.4.4" to "=3.4.4", it finally let me login!

When it was ">=3.4.4", it was installing 3.5.0 of authlogic, so it appears there is some change between 3.4.4 and 3.5.0 that is causing fatfreecrm to fail.

Hopefully this gets resolved in the actual codebase but at least I have a temporary fix.

**Comment by tomordonez** [comment]
The issue also appears with Ruby 2.3.0.

I used this fix and it seems to work. Thanks.

Although it is taking 10-12s to load each layout :(

**Comment by CloCkWeRX** [comment]
Can I get someone to try current authlogic and the github 4.2 branch of rails as per #555 - if that fixes it; we can close this off and wait for rails 4.2.8/4.2.7.2 or whatever they call it.

Otherwise, I'll pin to authlogic 3.4.4

**Comment by ain** [comment]
Guys, please also make sure your secret token is not mismanaged. If the cookie fails, you'd get the same login failure.

**Comment by johnnyshields** [comment]
@tomordonez @patakijv can you confirm if the issue persists on latest master? Otherwise we'll close it.

**Comment by johnnyshields** [comment]
Closing as it believe this is fixed. Also we're upgrading to Devise anyway.
