### ISSUE TITLE
undefined method `each' for #<String:0x00000003a27a58>

### ISSUE THREAD

**Issue by logiminecrm** [fatfreecrm/fat_free_crm#523]
First, I do really apologize, since I'm still newbie on this.

I was trying to install Fat Free CRM by following the instruction on this following sites:

http://www.blogdugeek.fr/crm-installation-fat-free-crm-debian-squeeze/
http://guides.fatfreecrm.com/Setup-Linux-or-Mac-OS.html

As I follow the instructions, I've encounter some errors and resolved some. However, upon executing this command:

> RAILS_ENV=production rake db:create db:migrate crm:settings:load

I was stuck in this command line and here are the following errors that I've been stuck with:

rake aborted!

> NoMethodError: undefined method `each' for #
> /usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-4.2.6/lib/active_record/connection_adapters/connection_specification.rb:150:in `resolve_all'
> /usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb:69:in `resolve'
> /usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-4.2.6/lib/active_record/core.rb:46:in `configurations='
> /usr/local/rvm/gems/ruby-2.2.4/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:5:in `block (2 levels) in '
> /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
> /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `'
> Tasks: TOP => db:create => db:load_config (See full trace by running task with --trace)

As I've search for more related issue, I found some, but it's still no use and I've stuck on this for almost 2 weeks.

Please help me on this.

Also, here are some data that might be needed.

**Ruby Version**
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

**Rails Version**
Rails 4.2.6

Here are the error lines

**_connection_specification.rb_**

```
 def resolve(config)
      if config
        resolve_connection config
      elsif env = ActiveRecord::ConnectionHandling::RAILS_ENV.call
        resolve_symbol_connection env.to_sym
      else
        raise AdapterNotSpecified
      end
    end

    # Expands each key in @configurations hash into fully resolved hash
    def resolve_all
      config = configurations.dup
      config.each do |key, value|               <---- Error line
        config[key] = resolve(value) if value
      end
      config
    end
```
**_connection_handling.rb_**

```
class MergeAndResolveDefaultUrlConfig # :nodoc:
  def initialize(raw_configurations)
    @raw_config = raw_configurations.dup
    @env = DEFAULT_ENV.call.to_s
  end

  # Returns fully resolved connection hashes.
  # Merges connection information from `ENV['DATABASE_URL']` if available.
  def resolve
    Error line ---->    ConnectionAdapters::ConnectionSpecification::Resolver.new(config).resolve_all 
  end

  private
    def config
      @raw_config.dup.tap do |cfg|
        if url = ENV['DATABASE_URL']
          cfg[@env] ||= {}
          cfg[@env]["url"] ||= url
        end
      end
    end
```
**_core.rb_**
```

def self.configurations=(config)
    Error line --->     @@configurations = ActiveRecord::ConnectionHandling::MergeAndResolveDefaultUrlConfig.new(config).resolve
  end
  self.configurations = {}

  # Returns fully resolved configurations hash
  def self.configurations
    @@configurations
  end
```

**_databases.rake_**

```
db_namespace = namespace :db do task :load_config do
Error line ---->   ActiveRecord::Base.configurations       = ActiveRecord::Tasks::DatabaseTasks.database_configuration || {}
ActiveRecord::Migrator.migrations_paths = ActiveRecord::Tasks::DatabaseTasks.migrations_paths
```
Hope to hear and seek some advises and learning. If there's need some more information, let me know.

Thanks,

**Comment by johnnyshields** [comment]
@logiminecrm can you confirm if the issue persists? Otherwise we'll close it.

**Comment by johnnyshields** [comment]
Please reopen if issue persists.
