### ISSUE TITLE
How about some kind of beta or alpha release on rubygems?

### ISSUE THREAD

**Issue by klyonrad** [fatfreecrm/fat_free_crm#533]
There are 266 (!!) commits to the master branch since [the last release](https://github.com/fatfreecrm/fat_free_crm/releases/tag/v0.13.6)

Wouldn't it be nice if you could simply declare a new version at some more recent commit and add a `-alpha` suffix to it? Cluttering a Gemfile with dependencies to a git repository is not so nice...

**Comment by CloCkWeRX** [comment]
#529 also. I might do a (very gentle) fork and hand out access to more folks

**Comment by CloCkWeRX** [comment]
I forked and published https://rubygems.org/gems/reduced_fat_crm

**Comment by klyonrad** [comment]
That's just a little _too eager_, I'd grant the maintainer some time. Also I do not want to meddle in the official, that's why I propose the `alpha` suffix in the version...

**Comment by CloCkWeRX** [comment]
0.14.0, 0.15.0-beta published
