### ISSUE TITLE
rainbow gem failure on Ruby 2.4

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#551]
On Ruby `2.4` I'm getting a following native extension build failure:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    can't modify frozen String

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.4.0/gems/rainbow-2.2.1 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.4.0/extensions/x86_64-linux/2.4.0/rainbow-2.2.1/gem_make.out

An error occurred while installing rainbow (2.2.1), and Bundler cannot continue.
Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.
```

Platform: `phusion/passenger-ruby24`

**Comment by ain** [comment]
Seems to be an issue discussed at sickill/rainbow#49

**Comment by ain** [comment]
I also noticed [`2.4` test is commented out](https://github.com/fatfreecrm/fat_free_crm/blob/master/.travis.yml#L5), was this one of the reasons?

**Comment by CloCkWeRX** [comment]
Pin to <= 2.2.1 for now is the fastest workaround; thought I'd done it for ffcrm but apparently not!

**Comment by CloCkWeRX** [comment]
> I also noticed 2.4 test is commented out, was this one of the reasons?
7af4f5aa - I suspect so.

**Comment by CloCkWeRX** [comment]
@ain take a look at the above linked ticket; think you are going to have a bad time with Ruby 2.4.0 and Rails 4.2.X for a bit.

Rails 5 for ffcrm is probably not guaranteed to work happily either without work.

**Comment by ain** [comment]
Thanks a lof for the prompt support!
