### ISSUE TITLE
Ensure compatibility with Ruby 2.4.0

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#553]
Was #551 

https://travis-ci.org/fatfreecrm/fat_free_crm/jobs/197180717 - not quite so working.

https://github.com/rails/rails/pull/27473 probably will help

**Comment by ain** [comment]
Build failure reproduced locally. Having exact same failure with `phusion/passenger-ruby24` and `rails 4.2.7.1`.

**Comment by ain** [comment]
I can confirm setting Rails dependency in `Gemfile` to

```ruby
gem 'rails', github: 'rails/rails', branch: '4-2-stable'
```
 resolves the problem.

**Comment by CloCkWeRX** [comment]
Have pushed something to point temporarily at github rails; will see what else breaks

**Comment by ain** [comment]
I tested `2.4` further today and faced #555. Doesn't look like a problem from the Ruby version, or?

**Comment by ain** [comment]
I'm calling for `v0.15.0-beta2` release from the `ruby_2.4.0` branch as it works.

**Comment by CloCkWeRX** [comment]
I'm kinda keen on the corresponding 4.2.* rails release to happen first I think - there's a small risk of bugs or changes that happen on the rails side of things that upset things further. That said, github is still an option

**Comment by CloCkWeRX** [comment]
I googled a bit, but couldn't really find any published timelines for when it might be released. Lets say... if its not out by 1st of March, I'll push a release then pointing at github.

**Comment by ain** [comment]
Beta release would be OK to be based like that I think, but stable would of course have to point to a Rails tag (master). 

Basecamp switched to `5.1.0.alpha` just recently as [they consider master to be very stable](https://twitter.com/dhh/status/824263601749917697).

**Comment by CloCkWeRX** [comment]
Pushed a 0.15.0-beta.2 release if you wanted to try that out.
