### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#554]
Blocked by https://github.com/rails/rails-observers/pull/41/files as well as probably other things

**Comment by kirantpatil** [comment]
Hi @CloCkWeRX 

Any updates on this issue ?

Thanks.

**Comment by azeemh** [comment]
Hi looking to build a project where we use fat free crm in a rails 5 project. Would prefer support for 5.1.x  in the spirit of keeping up to date. Please inform as to how I can help.

**Comment by CloCkWeRX** [comment]
In #608 I've made a start on this. Please feel free to clone the rails5 branch and submit pull requests to fix deprecations, bugs, etc.
