### ISSUE TITLE
Systematic login failure on admin by ffcrm:setup 

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#555]
__Steps to reproduce__:

1. Create new Rails project
2. Add `fat_free_crm` and Rails 4.2 gems to Gemfile

    ```ruby
    gem 'fat_free_crm', '~> 0.15.0.beta'
    gem 'rails', github: 'rails/rails', branch: '4-2-stable'
    ```
3. Bundle

    ```
    $ bundle
    ```
4. Run setup

    ```
    $ bundle exec rake ffcrm:setup
    ```
5. Provide credentials as prompted
6. Try to login

__What happens__: _Invalid username or password._ error is thrown. Database entry on user exists, but login fails.

__What should happen__: Login should succeed as by credentials entered during setup.

Database used: `mariadb:10.1`.

**Comment by ain** [comment]
I can spot a few
```
/usr/local/rvm/gems/ruby-2.4.0/gems/thread_safe-0.3.5/lib/thread_safe/cache.rb:155: warning: constant ::Fixnum is deprecated
```
warnings on console, but that can not be crucial as user entry is there in the database and the account generation does not fail.

**Comment by CloCkWeRX** [comment]
To pin it down a little further, try:
```bundle exec rails c````
and
experiment to see if you can authenticate against the user with http://stackoverflow.com/questions/6724494/i-need-to-authenticate-a-user-directly-in-the-console-under-devise-how-can-i-do

If not, its a wrong password vs setup thing or bug in devise; if you can auth then its a wiring bug.

**Comment by ain** [comment]
Thanks for the quick response @CloCkWeRX.

Auth over Rails console works fine as well as command line `mysql` access to the database container. 

What did you have in mind by _wiring_?

**Comment by CloCkWeRX** [comment]
So the next thing to check is probably still with the console, but interacting with the ApplicationController - something like http://stackoverflow.com/questions/4929078/how-to-sign-in-a-user-using-devise-from-a-rails-console

If that works, its a browser/form submission/frontend data issue; if it fails then it'll be something about how devise is connected to the application.

One thing worth keeping in mind, because the rails 4.2 work is from github rather than a stable release; there might be a subtle regression there we just can't obviously see.

**Comment by ain** [comment]
Something I discovered now is that on every failed login, the `app_session` cookie value updates. Wasn't the case on older versions (tested on `v0.13.4`).

**Comment by ain** [comment]
After some debugging in `authentication_controller.rb`, `@authentication.to_json` comes back with 

```json
{"scope":null,"attempted_record":null,"remember_me":"0","errors":{"base":["You did not provide any details for authentication."]}}
```

So looks like a submission issue indeed.

**Comment by ain** [comment]
Using the following in `Gemfile` and running `bundle update` resolved the issue:
```ruby
gem 'fat_free_crm', github: 'fatfreecrm/fat_free_crm', ref: 'ca59028'
gem 'rails', github: 'rails/rails', branch: '4-2-stable'
```

On these grounds, closing the ticket.

**Comment by CloCkWeRX** [comment]
Excellent news, thanks for tracking that down :)

**Comment by CloCkWeRX** [comment]
I wonder if #520 is related; though that points to authlogic
