### ISSUE TITLE
custom_field: text-input fields min_length set to maximum by default

### ISSUE THREAD

**Issue by clawster** [fatfreecrm/fat_free_crm#563]
min_length is set to 255 or 64k for text-area by default and cannot be overridden.

```<textarea rows="7" class="text optional" maxlength="65535" minlength="65535" placeholder="xxxx" name="account[cf_test]" id="account_cf_test"></textarea>```

**Comment by CloCkWeRX** [comment]
So, I think its
```
 = f.input field.name, field.input_options.merge(:checked => checked)
```
... which sets the attributes.

```
  def input_options
    input_html = {}
    attributes.reject do |k, v|
      !%w(as collection disabled label placeholder required maxlength).include?(k) || v.blank?
    end.symbolize_keys.merge(input_html)
  end
```
That doesn't actually specify a minlength attribute in there; and only would if your ```fields``` table had that kind of column.

Are you able to check thats not the case? That might point us to a regression with the form rendering stuff or similar.

What version of FFCRM are you on?

**Comment by clawster** [comment]
I cloned the master branch and we are running on the commit 1a2b61c1fb6f142bc1fb8da71f23fb4d5c0417c1 

There was no minlength specified in the fields table, so I added that column.

`ALTER TABLE `fields`ADD COLUMN `minlength` int(11) DEFAULT '0';`

And also added minlength to the allowed options and that works, it does not feel like the optimal solution but not a ruby programmer...

` !%w(as collection disabled label placeholder required minlength maxlength).include?(k) || v.blank?`

I would say it would be a more clean solution to just add "minlength=0" to the options sent to the forms renderer by default. 
Or to fix so that the forms rendering class does not set "minlength" to the maximum value of the input type.

**Comment by clawster** [comment]
Seems like simple_form added minlength to the options in the latest release...

https://github.com/plataformatec/simple_form/blob/master/CHANGELOG.md#340

**Comment by ain** [comment]
Confirmed. It's not a problem on Safari, but Chrome that does actually evaluate against it and blocks the form submission completely.

**Comment by ain** [comment]
Confirmed also on latest master of 2fc6e23.

**Comment by che2on** [comment]
What is the solution for this? One of the custom fields which i am using is asking me to set the data greater than 255 characters while i want it to be around 0 to 60 characters how can i achieve this?

**Comment by ain** [comment]
@che2on my #582 that fixes it, is still pending some spec fixes, but is ready. I can hopefully sort this PR out this week.

**Comment by che2on** [comment]
Thanks a lot for the response.
![db describe](https://cloud.githubusercontent.com/assets/745730/25385108/8af9e6ba-29e0-11e7-9699-e63cd452935b.png)

Referring to screenshot i think i should add a new column minlength for fields table? I am sorry, i am confused a bit. i just want to add a field which is of 0 to 60 character length. which part can should i change now as a quick fix?

**Comment by ain** [comment]
It's not only a database-related problem. You can apply my PR for a quickfix.

**Comment by che2on** [comment]
Thanks. I am extremely sorry for the newbie question. What is a PR and how can I apply it? I just started using fatfreecrm and felt it is very nice with lots of features for lead management. I can wait, but it will be great if you tell me how to update to latest version OR to a version where only a particular file is changed ( custom field in my case)? 

I know to use rake and git commands. So if I have to download the PR which you have given, i should so some editing in a particular file and then do rake?  Just see if you can answer this.

Nonetheless, i will wait for the official fix.

**Comment by che2on** [comment]
I think I should make following changes as given by you here: https://github.com/fatfreecrm/fat_free_crm/pull/582/commits/8c8b2a864fe0859aeebf85f881141d53c0c19306 and do rake?

**Comment by che2on** [comment]
I am giving it one more try - Help me with some git commands to pull this https://github.com/fatfreecrm/fat_free_crm/pull/582 and build ??

**Comment by che2on** [comment]
@ain Thanks a ton, made changes as found in pull #582  and did `rake db:migrate ` and it is working flawlessly!!!!
