### ISSUE TITLE
localhost-bound Account specs fail on Docker

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#578]
__Steps to reproduce__:

1. Set up FFCRM on Docker
2. Set up database

        $ RAILS_ENV=test bundle exec rake db:create
        $ RAILS_ENV=test bundle exec rake db:migrate

3. Run tests

        $ RAILS_ENV=test bundle exec rspec

__What happens__: account feature specs fail with:

``` 
remembers the comment field when the creation was unsuccessful
     Failure/Error: sock.bind(self)
     
     Errno::EADDRINUSE:
       Address already in use - bind(2) for 127.0.0.1:33100
     # /usr/local/rvm/gems/ruby-2.4.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:31:in `new'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:31:in `run'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/capybara-2.12.1/lib/capybara.rb:480:in `block in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/capybara-2.12.1/lib/capybara.rb:251:in `run_default_server'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/capybara-2.12.1/lib/capybara.rb:475:in `block in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.4.0/gems/capybara-2.12.1/lib/capybara/server.rb:101:in `block in boot'
```

__What should happen__: specs should be decoupled from localhost, tests should pass.

**Comment by CloCkWeRX** [comment]
I don't have much experience with docker itself TBH, but http://stackoverflow.com/questions/35821718/how-to-configure-capybara-to-run-tests-in-a-dockerized-selenium-grid might point in the right direction.

**Comment by ain** [comment]
Unfortunately no luck with it. Terribly sloppy and fragile setup with poor error handling from the Selenium community.

**Comment by johnnyshields** [comment]
Closing this as it appears to be a docker issue.

**Comment by ain** [comment]
I think the closing of this issue was premature. 

The fact that the tests run localhost hard-coded is not a Docker problem, it's a problem of test setup.

**Comment by CloCkWeRX** [comment]
Try 2ad0138 - wasn't quite sure where the app_url should be defined in the docker file; but it should solve half the problem.

**Comment by johnnyshields** [comment]
I've raised https://github.com/fatfreecrm/fat_free_crm/pull/715
