### ISSUE TITLE
Environment-aware host setting

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#597]
Currently the `:host:` in `config/settings.yml` expects single value, but how could we possibly deal with varying hosts as per environment (staging/production)?

It is relevant for manual testing on staging, using single URL wouldn't be satisfactory in that case.

Ideas, tips?

**Comment by CloCkWeRX** [comment]
I tend to deploy with chef and turn the config into a template, each environment with its own variables managed outside of it - specific jenkins builds kick off specific deploys for each env.

That said; FFCRM supports a settings table in a DB:

```
# Fat Free CRM settings are stored in three places, and are loaded in the following order:
#
# 1) config/settings.default.yml
# 2) config/settings.yml  (if exists)
# 3) 'settings' table in database  (if exists)
#
# Any configured settings in `config/settings.yml` will override those in
# `config/settings.default.yml`, and settings in the database table have the highest priority.

```
