### ISSUE TITLE
Attached documents to opportunities

### ISSUE THREAD

**Issue by chalmagean** [fatfreecrm/fat_free_crm#600]
I'm surprised there is no document upload functionality. Is this on purpose?

**Comment by CloCkWeRX** [comment]
There's a plugin for it (https://github.com/rapimo/crm_attachments) but at work we rolled our own  (account has many documents/uris to documents). I haven't looked at the plugin very much at all; so YMMV

**Comment by johnnyshields** [comment]
Given the fact that FFCRM supports avatar attachments already it really makes sense for document uploads to be part of the core functionality.

**Comment by steveyken** [comment]
Agree, file upload would make sense overall.

If it helps, we wrote a plugin for this too https://github.com/crossroads/ffcrm_attachments - I don't mind if that gets incorporated directly into the CRM unless there is a better approach these days.

**Comment by CloCkWeRX** [comment]
Let's give it a go in the next few months

**Comment by johnnyshields** [comment]
Replaced by #721
