### ISSUE TITLE
Change heroku guides link in readme

### ISSUE THREAD

**Issue by joren** [fatfreecrm/fat_free_crm#606]
Now http://guides.fatfreecrm.com/Setup-Heroku.html links to https://github.com/fatfreecrm/fat_free_crm/wiki/Setup-Heroku.html but the wiki link is https://github.com/fatfreecrm/fat_free_crm/wiki/Setup-Heroku

I assume you want to keep the `guides`-link, so I can't change the redirect myself.

**Comment by johnnyshields** [comment]
Fixed by 0cc4881e393aebec7d5cf1b099887c8e9efdfc75
