### ISSUE TITLE
Support rails 5.1 / Can not install do to gem dependency issues, can this be fixed soon?

### ISSUE THREAD

**Issue by elmo** [fatfreecrm/fat_free_crm#619]
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.3)

    fat_free_crm was resolved to 0.15.0.beta.2, which depends on
      rails (~> 5.0.0)

**Comment by CloCkWeRX** [comment]
#633
