### ISSUE TITLE
Cannot access online demo

### ISSUE THREAD

**Issue by richbl** [fatfreecrm/fat_free_crm#622]
DOES: Trying to log in with username:aaron and password:aaron fails with the error "Invalid username or password."

SHOULD: According the website, aaron:aaron should allow me to log into the online demo.

My guess would be that perhaps the demo grants admin permissions and someone changed the password of the username (aaron in this case) to something other than aaron.

Thanks

**Comment by saviokmua** [comment]
now all work fine

**Comment by richbl** [comment]
It does. It must've been a transient issue. Thanks
