### ISSUE TITLE
Can't select variables to filter by in Recent Activity

### ISSUE THREAD

**Issue by mesmerze** [fatfreecrm/fat_free_crm#694]
![activities](https://user-images.githubusercontent.com/16397590/35034561-a42cc028-fb7f-11e7-8d3e-038b9ace4764.png)

**Comment by CloCkWeRX** [comment]
Any JS console output?

Which versions are you comparing?

**Comment by johnnyshields** [comment]
No JS console output. This is a bug on master, I think he's comparing against the public demo.
