### ISSUE TITLE
Demo Site is Down

### ISSUE THREAD

**Issue by johnnyshields** [fatfreecrm/fat_free_crm#716]
http://demo.fatfreecrm.com/

returns 503 Service Unavailable

**Comment by steveyken** [comment]
If it helps, I can take a look at this one tomorrow.

**Comment by jtoy** [comment]
still down, important for potential users

**Comment by juanhck** [comment]
Looks like its still down, can I do something to help get it back up?

**Comment by kurtm** [comment]
Still down.

**Comment by schadenfred** [comment]
This may be the same issue as here:

https://github.com/fatfreecrm/fat_free_crm/issues/783

**Comment by steveyken** [comment]
It's back up now. I've set puma to auto start so we should be good again. Need to upgrade to the latest version of FFCRM though.
