### ISSUE TITLE
Regression: Select2 account selection controls have mixed initial state

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#718]
1. Opportunities
 2. Create
 3. Click 'select existing'
 4. Click 'create'

Expected:
UI returns to initial state

Actual:
UI is in a mixed state - both controls are visible.

<img width="845" alt="screen shot 2018-01-21 at 12 53 36 am" src="https://user-images.githubusercontent.com/365751/35184432-a735aa0a-fe45-11e7-8440-2eb08f16e592.png">

**Comment by johnnyshields** [comment]
@DmitryAvramec please fix this issue and compare with 0.16.0 to confirm the fix.

**Comment by johnnyshields** [comment]
@CloCkWeRX @DmitryAvramec will handle this

**Comment by CloCkWeRX** [comment]
Oops, missed this, 0.17.3 it is.
