### ISSUE TITLE
Make "Comments" and "Notes" consistent

### ISSUE THREAD

**Issue by johnnyshields** [fatfreecrm/fat_free_crm#737]
Currently, the app uses the word "Comment" in some places and "Note" in the other for the same thing.

We should standardize the wording (I think comment everywhere) and make it visually consistent as well.

**Comment by robotscissors** [comment]
@johnnyshields Is this something I can help with?

**Comment by steveyken** [comment]
Please do! I agree with Johnny. Using Comments everywhere is a good idea.

Thanks again,
Steve

**Comment by CloCkWeRX** [comment]
Ah nice one, @robotscissors
