### ISSUE TITLE
Can't select task to account

### ISSUE THREAD

**Issue by DmitryAvramec** [fatfreecrm/fat_free_crm#747]
I have created task
![created task](https://user-images.githubusercontent.com/23083062/35570984-e002cba8-05e1-11e8-852a-2506828adba1.png)
I want to assignee this task to account
![cant select task to account](https://user-images.githubusercontent.com/23083062/35571049-0cb1963e-05e2-11e8-98db-07def832576d.png)
Console error
![consloe error](https://user-images.githubusercontent.com/23083062/35571078-298b6780-05e2-11e8-9a95-54dd70b8cb34.png)

Steps to reproduce:
1. Create task
2. Create account
3. Go to this account page (accounts/1)
4. Select Task
5. Write task name

Same for all entities
Works on 0.16.x

**Comment by CloCkWeRX** [comment]
```
      $.extend $.ui.autocomplete::,
        _renderItem: (ul, item) ->
          term = new RegExp( "(" + @element.val() + ")", "gi" )
          html = item.label.replace(term, "<span class=\"jumpbox-highlight\">$1</span>")
          $("<li></li>").data("item.autocomplete", item).append($("<a></a>").html(html)).appendTo ul
```

**Comment by johnnyshields** [comment]
@DmitryAvramec is this fixed now?

**Comment by DmitryAvramec** [comment]
@johnnyshields nope, it's still dont work

**Comment by johnnyshields** [comment]
@DmitryAvramec can you please fix this?
