### ISSUE TITLE
undefined method `match?'

### ISSUE THREAD

**Issue by noahfin** [fatfreecrm/fat_free_crm#766]
I install everything correctly I believe and I am using ruby version 2.3.4.  I ran the demo set up and then tried to log in and got this error.     

undefined method `match?'

```
 def to_url
    match?(/^https?:\/\//) ? self : "http://#{self}"
  end
```
Called from `fat_free_crm-master/lib/fat_free_crm/core_ext/string.rb:`
I search the files and cant seem to fin match? declared. I see ruby has a built-in method match. Do I need to change all the method calls to `match`?. Or does anyone have the code in their app and know what the issue is?

**Comment by warrencohn** [comment]
I was having a similar issue. I am new to rails but found the post below that match was part of rails 2.4. Once I switched my version to 2.4.2 and bundled, it worked.

https://stackoverflow.com/questions/41792348/nomethoderror-undefined-method-match-for-rubystring

Warren

**Comment by noahfin** [comment]
Ok, thanks, Warren I thought it was, because of the using this version of ruby. Hopefully, they will fix the bug or put in the Readme that the current version of fat_free_crm is not compatible with 2.3.4 and I assuming other fairly new versions of ruby.

**Comment by CloCkWeRX** [comment]
See #665 - master branch has dropped ruby 2.3 or lower.
