### ISSUE TITLE
docker-compose build then run doesn't seem to work

### ISSUE THREAD

**Issue by tachang** [fatfreecrm/fat_free_crm#774]
web_1  | [ E 2018-04-06 15:54:07.3402 31/Tw age/Cor/App/Implementation.cpp:305 ]: Could not spawn process for application /home/app: An error occurred while starting up the preloader.
web_1  |   Error ID: 015e7aa3
web_1  |   Error details saved to: /tmp/passenger-error-PNUDbD.html
web_1  |   Message from application: cannot load such file -- bundler/dep_proxy (LoadError)

**Comment by tachang** [comment]
I had to shell in and do apt-get install tzdata

**Comment by tachang** [comment]
Also had to do

```
chown -R app:app tmp/
```

**Comment by WMPayne** [comment]
I created a new docker-compose file to try to alleviate this problem. See #787 for details.

**Comment by CloCkWeRX** [comment]
Closing due to #800
