### ISSUE TITLE
heroku instructions currently lead to crashing

### ISSUE THREAD

**Issue by schadenfred** [fatfreecrm/fat_free_crm#783]
I followed these instructions without loading sample data. 

https://github.com/fatfreecrm/fat_free_crm/wiki/Setup-Heroku

Code pushes, app starts, but then crashes. I believe the issue is that there's an instruction in the Procfile like this:

web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb

However according to the changelog:

- #641 Swap default server from thin/unicorn to puma

fatfreecrm is no longer using unicorn as default. I removed the line in the procfile (but left the empty prrocfile) and it seems to run. Here's a pull request with the change, however it probably breaks other deployment instruction sets:

https://github.com/fatfreecrm/fat_free_crm/pull/782

**Comment by CloCkWeRX** [comment]
@johnnyshields

**Comment by CloCkWeRX** [comment]
#782
