### ISSUE TITLE
Can't Save Task "On Specific Date ..."

### ISSUE THREAD

**Issue by pbraswell** [fatfreecrm/fat_free_crm#789]
I'd like to create a task to be due on a specific date. When I choose "On Specific Date..." and choose a date from the chooser, I would expect the dialog to close and the task to be saved after clicking the 'save' button but it doesn't. 

In the Heroku logs, I can see a POST come through to /tasks/1 but nothing seems to be saved and there are no additional messages, error or otherwise in the logs. What am I doing wrong?

Many thanks,
Peter

**Comment by ken-wong** [comment]
Find the file named: `tasks_controller.rb`
change the code(line#188) from:
```ruby
      :background_info
```
to 
```ruby
      :background_info,
      :calendar
```

**Comment by williamn** [comment]
@ken-wong it works. Is there any PR for this already?

**Comment by ken-wong** [comment]
@williamn the PR is made [791](https://github.com/fatfreecrm/fat_free_crm/pull/791)
