### ISSUE TITLE
Import NEW emails not related to dropbox or comments/replies

### ISSUE THREAD

**Issue by user00265** [fatfreecrm/fat_free_crm#790]
Hi,

Is there a way to pull emails that are not related to dropbox (BCC emails) or comments/replies (to existing messages), especially those coming from addresses that are not users on FFCRM?

For example, if a customer emails the customer service desk, and we have a contact  or account for the sender email, import it and associated it with that record, and skip it from processing by the other processes (dropbox and comments_replies).

This would aid a lot in having everybody CC or BCC the dropbox email address and save time to our company.

**Comment by CloCkWeRX** [comment]
Unfortunately no, I don't believe so
