### ISSUE TITLE
Changing primary keys to UUIDs

### ISSUE THREAD

**Issue by meerman** [fatfreecrm/fat_free_crm#793]
I need to use UUIDs as the primary key. This is because the keys need to be globally unique. 

The application is new, so there is no legacy database. As far as I can tell, changing the identifiers and the references to UUIDs should work.

Should I implement this feature as a patch for this repo or as a plugin (or something else)?

**Comment by cornishpirate** [comment]
I understand the desire for this but why do this via primary keys? If you are looking for globally unique identifiers, you could consider adding a uuid field to the entities you're after, then using that as your `identifier` and referencing via the controller with `defaults finder: :find_by_identifier!` and `load_resource find_by: :identifier`

**Comment by meerman** [comment]
That would also work. I'm used to having UUIDs as primary keys. Your approach would definitely work, I'll stick to that. Thanks.
