### ISSUE TITLE
Suggestion: Use Dependabot to keep dependencies up-to-date / secure

### ISSUE THREAD

**Issue by greysteil** [fatfreecrm/fat_free_crm#799]
I noticed https://github.com/fatfreecrm/fat_free_crm/commit/3df473a9e9bd468ee25b43eee09e73ef69431b7c so wanted to suggest the tool I built, [Dependabot](https://dependabot.com) to automatically create PRs for dependency updates. It can be put in security-only mode if helpful, and is of course totally free for open source.

Also worth mentioning that you'd be helping the community by using it because it aggregates the results of everyone's test runs when updating a dependency, and will soon use that data to report back any bugs to the dependency maintainer.

**Comment by adamlfoater** [comment]
Hi,
I'm looking for someone who can help me customise my own version of FatFreeCRM to fit my business of advertising sales. Can you or anyone help?

**Comment by CloCkWeRX** [comment]
@steveyken, could you take a look at this? An example that works well I've seen is how it runs https://github.com/Growstuff/growstuff/pulls

We're in a good position with various gems being pinned, and the tests will eventually pass if frowned at enough; so this reduces maintenance to a few clicks per dependency.

**Comment by steveyken** [comment]
I like the idea. I've used Dependabot on some other OS reps and I do feel it adds some useful value to this project, esp if we can sort our test runs again as you mentioned... feels close!

**Comment by CloCkWeRX** [comment]
Tests seem *almost* stable - ie, to get the build green is just a matter of running the failed job once more, and that usually gets it over the line. I may put more things into allowed failures or exclude running feature specs across so many versions of ruby.

**Comment by CloCkWeRX** [comment]
Part of github's offerings nowdays.
