### ISSUE TITLE
Login form layout broken on 0.19.0

### ISSUE THREAD

**Issue by ain** [fatfreecrm/fat_free_crm#806]
Compared to `v0.13.6 `

<img width="583" alt="screenshot 2018-11-12 at 21 49 11" src="https://user-images.githubusercontent.com/370576/48374324-d10bf380-e6c4-11e8-93d0-24e325acb03e.png">

the login form of `v0.19.0` comes across broken:

<img width="895" alt="screenshot 2018-11-12 at 21 47 02" src="https://user-images.githubusercontent.com/370576/48374277-ade14400-e6c4-11e8-9a4e-f4a2d5ebb6a7.png">

Current FFCRM runs as Rails engine.

**Comment by CloCkWeRX** [comment]
Part of #742 / the changeover to devise. But yes, worth making a little better looking!

**Comment by CloCkWeRX** [comment]
This is probably the only thing left that I'd change before cutting an 0.19.0 release - PRs welcome!

**Comment by CloCkWeRX** [comment]
Going to close - its ugly, but... it works.
