### ISSUE TITLE
Errror time format in fr localization

### ISSUE THREAD

**Issue by yet-a-teapot** [fatfreecrm/fat_free_crm#809]
Hello

There’s an extra percent at end in line 813 in `config/locales/fat_free_crm.fr.yml` for `mmddhhss:` time format pattern.
```
813c813
<       mmddhhss: ! '%b %e à %H:%M%'
---
>       mmddhhss: ! '%b %e à %H:%M'

```

**Comment by yet-a-teapot** [comment]
Hello

There’s an extra percent at end in line 813 in `config/locales/fat_free_crm.fr.yml` for  `mmddhhss:` time format pattern.

```
813c813
<       mmddhhss: ! '%b %e à %H:%M%'
---
>   
```

**Comment by steveyken** [comment]
Thanks, this is now fixed on master
