### ISSUE TITLE
Demo login doesn't work

### ISSUE THREAD

**Issue by pablopla** [fatfreecrm/fat_free_crm#826]
I've tried login to the demo with aaron:aaron but getting an error
```Invalid Email or password.```
http://demo.fatfreecrm.com/users/sign_in

**Comment by deepnirmal** [comment]
Yeah even for me

**Comment by NieBoy** [comment]
+1

**Comment by aslam** [comment]
You can try any other username/password combinations listed in [this page](https://github.com/fatfreecrm/fat_free_crm/wiki/Setup-Linux-or-Mac-OS#load-demo-data-optional). The first one aaron/aaron is not working but ben/ben works.

**Comment by steveyken** [comment]
This is fixed now. Apologies for the delay
