### ISSUE TITLE
Creating user in rails console fails

### ISSUE THREAD

**Issue by mapreal19** [fatfreecrm/fat_free_crm#858]
Hi! I've installed the crm (v0.18.1) as an engine in a new Rails 5.1 app. I now try to create a user in the console but validation fails:

![image](https://user-images.githubusercontent.com/3055997/70717543-d932ca00-1cee-11ea-99d7-538abbe48ec2.png)

 If I save with `save!` I receive this message: `ActiveRecord::RecordInvalid (Validation failed: Related must exist, User must exist)`

Also another minor issue: I needed to add this in my assets file: `Rails.application.config.assets.precompile += %w[*.png *.jpg *.jpeg *.gif]`

**Comment by CloCkWeRX** [comment]
https://www.ombulabs.com/blog/rails/upgrades/upgrade-rails-from-5-0-to-5-1.html will help for any configuration changes.

**Comment by CloCkWeRX** [comment]
https://edgeguides.rubyonrails.org/association_basics.html#optional is the behaviour change that makes things non optional by default. Potentially some cases are missed. Feel free to throw in a PR.

**Comment by mapreal19** [comment]
@CloCkWeRX is this going to be handled in https://github.com/fatfreecrm/fat_free_crm/pull/854 ?

**Comment by mapreal19** [comment]
Instead of adding `optional` to those models I added this option to my config:

`config.active_record.belongs_to_required_by_default = false`

From: https://stackoverflow.com/a/40895199/2273578

May be a faster option for upgrading to Rails 5.2. Then we could add those optionals later
