### ISSUE TITLE
Switching to "ru" locale gives Error 500 on most of tabs except Tasks

### ISSUE THREAD

**Issue by vabods** [fatfreecrm/fat_free_crm#859]
Hello
Running Fat Free CRM version 0.18.1 (mysql2). 
All works ok. When changed to "ru" locale in settings.default.yml file and services restart gives Error 500 on accessing  /opportunities, /campaigns, /leads, /accounts 
Works ok on /tasks
Locales ja, pt-BR, en-GB and others don't have this issue

OS 
cat /etc/os-release 
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"

LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

locale -a
C
C.UTF-8
en_US.utf8
POSIX
ru_RU
ru_RU.iso88595
ru_RU.utf8

**Comment by vabods** [comment]
Problem was here

 Rendered contacts/index.html.haml within layouts/application (42.7ms)
Completed 500 Internal Server Error in 135ms (ActiveRecord: 10.2ms)
  
ActionView::Template::Error (translation data {:one=>"Найден %{count} результат.", :other=>"Найдено %{count} результатов."} can not be used with :count => 0. key 'many' is missing.):
     7:         = link_to t('advanced_search'), '#', :"data-search-form" => "advanced_search", class: (!params[:q] ? "" : " active")
     8: 
     9:     #search_results_count
    10:       = t('search_results_count', count: @search_results_count)
    11: 
    12:   .search_form#basic_search{ style: (params[:q] ? 'display: none;' : '') }
    13:     = render "basic_search"


lib/fat_free_crm/i18n.rb:17:in `t'
app/views/entities/_search.html.haml:10:in `_app_views_entities__search_html_haml__1260432373114741722_47385598310860'
app/views/contacts/index.html.haml:7:in `_app_views_contacts_index_html_haml___1609657042813816598_47385577640780'
app/controllers/entities/contacts_controller.rb:16:in `index'

Key 'many' was missing for file fat_free_crm.ru.yml

 basic_search: Основной поиск
  search_results_count:
    one: Найден %{count} результат.
  ==> This key was missing many: Найдено %{count} результатов.
    other: Найдено %{count} результатов.

**Comment by johnbumgardner** [comment]
@vabods I created a pull request fixing this. Would you mind checking it on your side?

**Comment by johnbumgardner** [comment]
@CloCkWeRX we can also close this issue i believe
