### ISSUE TITLE
Regression: features/leads_spec not creating lead

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#873]
![image](https://user-images.githubusercontent.com/365751/83705466-2b2c2b00-a654-11ea-8aa2-f14d8affd869.png)

This test fails on an empty DB; but succeeds if you pause with a debugger.

I suspect its not loading the business address form elements fully

![image](https://user-images.githubusercontent.com/365751/83705946-6b3fdd80-a655-11ea-94d9-35c25438142b.png)

**Comment by cornishpirate** [comment]
This is not a spec issue, but a code issue. Running in production on heroku, I am getting the exact same issue when trying to create a lead for the first time (using a clean database)

**Comment by cornishpirate** [comment]
Here's a screencast of the bug:


![lead-creation-error](https://user-images.githubusercontent.com/21303889/84746701-4846ef00-afae-11ea-9eb3-eca386bc796c.gif)

**Comment by cornishpirate** [comment]
Working notes on this. When trying to create a lead in an empty db (after running ``, the sql trace is

```
FieldGroup Load (0.4ms)  SELECT "field_groups".* FROM "field_groups" WHERE "field_groups"."klass_name" = $1 AND (tag_id IS NULL OR tag_id IN (NULL)) ORDER BY "field_groups"."position" ASC  [["klass_name", "Lead"]]
  Setting Load (0.3ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "require_first_names"], ["LIMIT", 1]]
  Setting Load (0.2ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "require_last_names"], ["LIMIT", 1]]
  Setting Load (0.2ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "lead_status"], ["LIMIT", 1]]
   (0.2ms)  ROLLBACK
```

The issue appears to be in the field_groups and settings selects as there are no entries in those tables. 

Attempt 1: `bin/rails db:seed`
Result: db/seeds.rb is empty, so no data loaded

Attempt 2: uncomment `require Rails.root.join('db/seeds/fields')` and run `bin/rails db:seed`
Result: 

```sh
rails aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'tooltip' for FieldGroup.
```

Attempt 3: remove `, tooltip: ''` from `db/seeds/fields.rb`
Result:

```sh
rails aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'field_type' for Field.
```

Attempt 4: remove `field_type: '', ` from `db/seeds/fields.rb`
Result: Seeds loaded, but error still persists
