### ISSUE TITLE
Demo login doesn't work

### ISSUE THREAD

**Issue by jenxi** [fatfreecrm/fat_free_crm#880]
I tried logging into the demo with aaron:aaron but it says `Invalid Email or password.`
http://demo.fatfreecrm.com/users/sign_in

**Comment by 80boys** [comment]
Demo login doesn't work

**Comment by djrobby** [comment]
Demo login doesn't work

**Comment by coreyaus** [comment]
Hey team - I just had the same issue. The good news is that you can access the demo using one of these username and password combos: https://github.com/fatfreecrm/fat_free_crm/wiki/Setup-Linux-or-Mac-OS#load-demo-data-optional

**Comment by djrobby** [comment]
@coreyaus aaron/aaron combination does not work. All others do.

**Comment by steveyken** [comment]
The online demo has been removed now. We'll work on a way to get a docker image with demo data that can be easily spun up in https://github.com/fatfreecrm/fat_free_crm/issues/1017 This will address issues where some users log in with the credentials above and change the password :)
