### ISSUE TITLE
Adopt a new color pallete

### ISSUE THREAD

**Issue by CloCkWeRX** [fatfreecrm/fat_free_crm#906]
Part of #695

Proposal:
https://coolors.co/264653-2a9d8f-e9c46a-f4a261-e76f51

This is something we could fairly easy adjust the current CSS to, outside of bootstrap or similar other visual overalls

Current:
![image](https://user-images.githubusercontent.com/365751/117396711-b3d4da80-af39-11eb-95e8-12f039113abd.png)

With pallette:
![image](https://user-images.githubusercontent.com/365751/117397460-5c376e80-af3b-11eb-9685-e35858f977e6.png)
 * No box shadows to flatten it all
 * Background is #F0DDA8
 
See also #908
 
 
![image](https://user-images.githubusercontent.com/365751/117397927-60b05700-af3c-11eb-9c5e-4d618799af07.png)
 * Swap to Roboto

![image](https://user-images.githubusercontent.com/365751/117398013-86d5f700-af3c-11eb-9877-7e5b4336bd97.png)

 * Lighten the dotted borders (See #907)
 
 
 
![image](https://user-images.githubusercontent.com/365751/117398367-5cd10480-af3d-11eb-8596-284210e20aab.png)

 * Lighten the heading underlines to #eee  (See #907)

![image](https://user-images.githubusercontent.com/365751/117398444-8be77600-af3d-11eb-88c8-f0837c6713a6.png)

 * Remove rounding on tags more (See #908 )

**Comment by CloCkWeRX** [comment]
Not exactly earth shattering, but makes us a bit more modern feeling with a limited colour pallette. Note, the tags in the "My Opportunities" section aren't changed over yet.

**Comment by johnbumgardner** [comment]
What do you think about a light/dark breakdown as well

**Comment by hubyhuby** [comment]
Very nice work. My two cents: the trend (that I like too) is for a cleaner interface. Too many things to see make your brain melt down :D 
Lots of interface removes things to present you with almost pure data, think gmail for example. I think fat free crm is not far at all from those standards. What we would need is a bite of CSS to make it look "whiter". There are definitely too many colors.
For example, we don t really care about the menu on top most of the time, excpet when we mouse over.

![image](https://github.com/fatfreecrm/fat_free_crm/assets/26340942/81a4903e-0263-4aa2-9f01-43e744d7db88)


Mockups

![image](https://github.com/fatfreecrm/fat_free_crm/assets/26340942/dbdcbac4-3f0a-4ce6-a737-05091d78ef15)

**Comment by CloCkWeRX** [comment]
I probably should close this one off, as the tags etc did get merged in.

I am not currently using FFCRM daily, but PRs certainly welcome for further design improvements - recommend doing small changes and a before/after screenshot.

**Comment by romanbsd** [comment]
> Very nice work. My two cents: the trend (that I like too) is for a cleaner interface. Too many things to see make your brain melt down :D Lots of interface removes things to present you with almost pure data, think gmail for example. I think fat free crm is not far at all from those standards. What we would need is a bite of CSS to make it look "whiter". There are definitely too many colors. For example, we don t really care about the menu on top most of the time, excpet when we mouse over.
> 
> Example of less colored interfaces : ![image](https://user-images.githubusercontent.com/26340942/257039608-81a4903e-0263-4aa2-9f01-43e744d7db88.png) In this example I would put the menu in negative : the blue is important it is where I am, and the rest of the menus are white so it doesn t overload the screen with colours
> 
> ![image](https://user-images.githubusercontent.com/26340942/257039652-dbdcbac4-3f0a-4ce6-a737-05091d78ef15.png)

Can you share your CSS, it looks great!

**Comment by ferrisoxide** [comment]
Can I suggest we also look towards supporting dark mode?

**Comment by hubyhuby** [comment]
@romanbsd ,
We have heavily modified fat free to have this look. Not only the CSS.
I don t think it would be usefull to send you a css.
