### ISSUE TITLE
My question

### ISSUE THREAD

**Issue by todaycodemaster** [fatfreecrm/fat_free_crm#948]
I just before started the Ruby on rails and this is good sample for me.
I tried to integration API on this project. I want to change the design with vue because this is not so fashion.

But in my API controller @ user and @ group etc not working.

But in the real controller it is working well.

what is the reason and how can I user the model name with @ like the real controller.

Please help me.

**Comment by johnbumgardner** [comment]
I'm not sure I follow. You want to use Fat Free CRM backend only and do your own front end?
